import type { PageTextSlot } from "../types";

// ---------------------------------------------------------------------------
// about (71, route: "/about")
// v2 Wave 1 (docs/design/visual-text-editor-v2.md §5): 既存7件 (hero/why/facility/gallery/cta
// 見出し・CTA・リード文) はそのまま維持し、page-body.tsx の残り全静的テキスト
// (rich 3件含む) を追加。defaultText は現行描画テキストと1文字も違わない (非退行)。
// shop.ts (Wave 1 の先行完了ページ) の配線スコープ方針を踏襲する:
// - PageHead index/en は対象に含める
// - SectionMark の `label` は対象に含めるが、`no` ("SEC. 01" 等) は対象外
//   (data-sec-no 属性値としてのみ使われる装飾的な連番のため、noSlotKey capability は
//   page-blocks.tsx 側に存在するが本 wave では配線しない)
// - PhotoFigure の capJa/capEn/credit は対象に含める
// rich kind の語彙は mono(`text`) / strong(**text**) / link([text](url)) の3種のみ (§3.1)。
// rich 3件: about.why.table.4.td (比較表最終行の強調文+平文) /
// about.facility.table.1.td・about.facility.table.2.td (仕様表の数値強調)。
// ---------------------------------------------------------------------------
export const ABOUT_TEXT_SLOTS: readonly PageTextSlot[] = [
  {
    key: "about.hero.heading",
    page: "about",
    route: "/about",
    label: "会社案内 / ヒーロー見出し",
    kind: "lines",
    maxLen: 36,
    defaultText: "下地の仕事は、\n見えなくなるからこそ。",
    maxLines: 2,
    maxLineLen: 20,
  },
  {
    key: "about.hero.lead",
    page: "about",
    route: "/about",
    label: "会社案内 / ヒーローリード文",
    kind: "multiline",
    maxLen: 200,
    defaultText:
      "仕上がった塗面に、研ぎの跡は残りません。それでも、艶の深さも、色の正確さも、すべては見えなくなった下地が決めています。隈部塗装は、その見えない工程に最も時間を割く工房です。",
  },
  {
    key: "about.why.heading",
    page: "about",
    route: "/about",
    label: "会社案内 / WHY THIS WORKSHOP 見出し",
    kind: "lines",
    maxLen: 40,
    defaultText: "「表面処理だけ頼みたい」に、\n応える工房が少なかった。",
    maxLines: 2,
  },
  {
    key: "about.facility.heading",
    page: "about",
    route: "/about",
    label: "会社案内 / FACILITY 見出し",
    kind: "text",
    maxLen: 24,
    defaultText: "バンパー6本を、同時に塗れる。",
  },
  {
    key: "about.gallery.heading",
    page: "about",
    route: "/about",
    label: "会社案内 / GALLERY 見出し",
    kind: "text",
    maxLen: 18,
    defaultText: "現場の、手ざわり。",
  },
  {
    key: "about.cta.heading",
    page: "about",
    route: "/about",
    label: "会社案内 / CTA帯 見出し",
    kind: "lines",
    maxLen: 44,
    defaultText: "工程と料金の詳細は、\nサービスページに。",
    maxLines: 2,
  },
  {
    key: "about.cta.note",
    page: "about",
    route: "/about",
    label: "会社案内 / CTA帯 補足",
    kind: "text",
    maxLen: 60,
    defaultText: "下地は全グレード共通。差分はトップコートの層数だけです。",
  },

  // ---- PageHead ----
  {
    key: "about.hero.index",
    page: "about",
    route: "/about",
    label: "会社案内 / PageHead 連番表記 (INDEX NN — ページ名)",
    kind: "text",
    maxLen: 25,
    defaultText: "INDEX 02 — ABOUT",
  },
  {
    key: "about.hero.en",
    page: "about",
    route: "/about",
    label: "会社案内 / PageHead 英字サブラベル",
    kind: "text",
    maxLen: 35,
    defaultText: "WORKSHOP & CRAFTSMAN",
  },

  // ---- SEC.01 WHY THIS WORKSHOP ----
  {
    key: "about.why.sec.label",
    page: "about",
    route: "/about",
    label: "会社案内 / SEC.01 セクションラベル",
    kind: "text",
    maxLen: 30,
    defaultText: "WHY THIS WORKSHOP",
  },
  {
    key: "about.why.table.1.th",
    page: "about",
    route: "/about",
    label: "会社案内 / WHY比較表 行1 見出し (大手3Dプリント業者)",
    kind: "text",
    maxLen: 20,
    defaultText: "大手3Dプリント業者",
  },
  {
    key: "about.why.table.1.td",
    page: "about",
    route: "/about",
    label: "会社案内 / WHY比較表 行1 本文",
    kind: "text",
    maxLen: 120,
    defaultText:
      "塗装は後加工オプション扱いで、多くは黒塗装・単色止まり。カスタム塗装は手動見積もりで、3コートパール等の高難度意匠塗装は稀。",
  },
  {
    key: "about.why.table.2.th",
    page: "about",
    route: "/about",
    label: "会社案内 / WHY比較表 行2 見出し (一般の塗装店)",
    kind: "text",
    maxLen: 16,
    defaultText: "一般の塗装店",
  },
  {
    key: "about.why.table.2.td",
    page: "about",
    route: "/about",
    label: "会社案内 / WHY比較表 行2 本文",
    kind: "text",
    maxLen: 100,
    defaultText:
      "塗装はできても、3Dプリント特有の積層痕処理を知らない。素材との相性や下地の作り方に、専用のノウハウが要ります。",
  },
  {
    key: "about.why.table.3.th",
    page: "about",
    route: "/about",
    label: "会社案内 / WHY比較表 行3 見出し (試作会社)",
    kind: "text",
    maxLen: 14,
    defaultText: "試作会社",
  },
  {
    key: "about.why.table.3.td",
    page: "about",
    route: "/about",
    label: "会社案内 / WHY比較表 行3 本文",
    kind: "text",
    maxLen: 120,
    defaultText:
      "デザインモデルの品質は表面処理で決まるにもかかわらず、表面処理を高水準で内製できる会社は少なく、「表面処理だけ外注したい」需要が存在します。",
  },
  {
    key: "about.why.table.4.th",
    page: "about",
    route: "/about",
    label: "会社案内 / WHY比較表 行4 見出し (隈部塗装)",
    kind: "text",
    maxLen: 12,
    defaultText: "隈部塗装",
  },
  {
    key: "about.why.table.4.td",
    page: "about",
    route: "/about",
    label: "会社案内 / WHY比較表 行4 本文 (rich, 強調+平文)",
    kind: "rich",
    maxLen: 220,
    defaultText:
      "**積層痕を消す研磨・自動車グレードの艶・3コートパールの意匠。3つ全部をひとりで持ち、その空白に正確に嵌まります。**海外では、顧客の試作品の仕上げ・塗装だけを専門に請け負うサービスが成立しており、世界大手の3Dプリンタメーカーも自動車塗装業者との協業事例を公開しています。「3Dプリント × 自動車塗装職人」は、業界の理想像そのものです。",
  },

  // ---- SEC.02 CRAFTSMAN ----
  {
    key: "about.craftsman.sec.label",
    page: "about",
    route: "/about",
    label: "会社案内 / SEC.02 セクションラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "CRAFTSMAN",
  },
  {
    key: "about.craftsman.name",
    page: "about",
    route: "/about",
    label: "会社案内 / 代表者名 (大見出し表示)",
    kind: "text",
    maxLen: 10,
    defaultText: "隈部 信之",
  },
  {
    key: "about.craftsman.romaji",
    page: "about",
    route: "/about",
    label: "会社案内 / 代表者名 ローマ字+肩書",
    kind: "text",
    maxLen: 55,
    defaultText: "KUMABE NOBUYUKI — REPRESENTATIVE / PAINTER",
  },
  {
    key: "about.craftsman.bio.1",
    page: "about",
    route: "/about",
    label: "会社案内 / 代表者紹介 本文1",
    kind: "text",
    maxLen: 140,
    defaultText:
      "家電の量産塗装の現場で、均一な膜厚管理・治具化・段取りを積み重ねてきた自動車塗装職人。「量産の精度」を体に入れ、いまはその技術のすべてを、3Dプリントの表面処理に注いでいます。",
  },
  {
    key: "about.craftsman.bio.2",
    page: "about",
    route: "/about",
    label: "会社案内 / 代表者紹介 本文2",
    kind: "text",
    maxLen: 150,
    defaultText:
      "一点ものを美しく塗ることと、同じ品質で数を仕上げることは、別の技術です。量産塗装の現場は、後者を毎日要求します。だから、あなたの一点の勝負試作と、千個のブリッジ生産を、同じ品質基準で仕上げられます。",
  },

  // ---- SEC.03 FACILITY ----
  {
    key: "about.facility.sec.label",
    page: "about",
    route: "/about",
    label: "会社案内 / SEC.03 セクションラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "FACILITY",
  },
  {
    key: "about.facility.lead",
    page: "about",
    route: "/about",
    label: "会社案内 / FACILITY リード文 (SecLead内埋め込みのため text kind)",
    kind: "text",
    maxLen: 110,
    defaultText:
      "同時処理能力は、そのまま数量対応力と価格に反映されます。面を埋めるほど1個あたりの手間は下がる——バッチ処理は、この工房の価格競争力の源泉です。",
  },
  {
    key: "about.facility.table.1.th",
    page: "about",
    route: "/about",
    label: "会社案内 / 設備表 行1 見出し (塗装ブース)",
    kind: "text",
    maxLen: 14,
    defaultText: "塗装ブース",
  },
  {
    key: "about.facility.table.1.td",
    page: "about",
    route: "/about",
    label: "会社案内 / 設備表 行1 本文 (rich, 本数強調)",
    kind: "rich",
    maxLen: 60,
    defaultText: "乗用車のバンパー**6本**を同時に塗装できる常設ブース。",
  },
  {
    key: "about.facility.table.2.th",
    page: "about",
    route: "/about",
    label: "会社案内 / 設備表 行2 見出し (バッチ処理能力)",
    kind: "text",
    maxLen: 16,
    defaultText: "バッチ処理能力",
  },
  {
    key: "about.facility.table.2.td",
    page: "about",
    route: "/about",
    label: "会社案内 / 設備表 行2 本文 (rich, 個数強調×2)",
    kind: "rich",
    maxLen: 90,
    defaultText:
      "**200×200mm級 — 約30個** / **30×200mm級 — 100個超** を同時処理。",
  },
  {
    key: "about.facility.table.3.th",
    page: "about",
    route: "/about",
    label: "会社案内 / 設備表 行3 見出し (塗料システム)",
    kind: "text",
    maxLen: 16,
    defaultText: "塗料システム",
  },
  {
    key: "about.facility.table.3.td",
    page: "about",
    route: "/about",
    label: "会社案内 / 設備表 行3 本文",
    kind: "text",
    maxLen: 90,
    defaultText:
      "自動車補修用2液ウレタン（主剤＋硬化剤の化学反応で常温硬化）。市販の調色済み補修塗料を正規用途で使用。",
  },
  {
    key: "about.facility.table.4.th",
    page: "about",
    route: "/about",
    label: "会社案内 / 設備表 行4 見出し (硬化)",
    kind: "text",
    maxLen: 10,
    defaultText: "硬化",
  },
  {
    key: "about.facility.table.4.td",
    page: "about",
    route: "/about",
    label: "会社案内 / 設備表 行4 本文",
    kind: "text",
    maxLen: 90,
    defaultText:
      "常温硬化（表面乾燥1〜3時間 / 完全硬化5〜7日）。赤外線ヒーターは納期短縮・回転率向上の道具として小〜中型に併用。",
  },
  {
    key: "about.facility.table.5.th",
    page: "about",
    route: "/about",
    label: "会社案内 / 設備表 行5 見出し (安全管理)",
    kind: "text",
    maxLen: 14,
    defaultText: "安全管理",
  },
  {
    key: "about.facility.table.5.td",
    page: "about",
    route: "/about",
    label: "会社案内 / 設備表 行5 本文",
    kind: "text",
    maxLen: 100,
    defaultText:
      "塗装作業中（溶剤蒸気がある間）の火気は厳禁。石油燃焼機器の使用は、塗装後に換気を経てからの雰囲気加熱に限定しています。",
  },
  {
    key: "about.facility.1.capja",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.01 (設備写真) 日本語キャプション",
    kind: "text",
    maxLen: 16,
    defaultText: "吹き付けの設備",
  },
  {
    key: "about.facility.1.capen",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.01 (設備写真) 英語キャプション",
    kind: "text",
    maxLen: 26,
    defaultText: "SPRAY EQUIPMENT",
  },
  {
    key: "about.facility.1.credit",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.01 (設備写真) クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: kagan_4854 / Unsplash",
  },
  {
    key: "about.facility.2.capja",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.02 (工具写真) 日本語キャプション",
    kind: "text",
    maxLen: 16,
    defaultText: "整然と並ぶ工具",
  },
  {
    key: "about.facility.2.capen",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.02 (工具写真) 英語キャプション",
    kind: "text",
    maxLen: 22,
    defaultText: "THE TOOLING",
  },
  {
    key: "about.facility.2.credit",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.02 (工具写真) クレジット表記",
    kind: "text",
    maxLen: 40,
    defaultText: "Photo: volft / Unsplash",
  },
  {
    key: "about.facility.3.capja",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.03 (機械写真) 日本語キャプション",
    kind: "text",
    maxLen: 14,
    defaultText: "工房の機械",
  },
  {
    key: "about.facility.3.capen",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.03 (機械写真) 英語キャプション",
    kind: "text",
    maxLen: 24,
    defaultText: "THE MACHINERY",
  },
  {
    key: "about.facility.3.credit",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.03 (機械写真) クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: kadircelep / Unsplash",
  },

  // ---- SEC.04 PROFILE ----
  {
    key: "about.profile.sec.label",
    page: "about",
    route: "/about",
    label: "会社案内 / SEC.04 セクションラベル",
    kind: "text",
    maxLen: 16,
    defaultText: "PROFILE",
  },
  {
    key: "about.profile.heading",
    page: "about",
    route: "/about",
    label: "会社案内 / PROFILE 見出し",
    kind: "text",
    maxLen: 12,
    defaultText: "会社概要",
  },
  {
    key: "about.profile.table.1.th",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行1 見出し (屋号)",
    kind: "text",
    maxLen: 10,
    defaultText: "屋号",
  },
  {
    key: "about.profile.table.1.td",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行1 本文",
    kind: "text",
    maxLen: 24,
    defaultText: "隈部塗装（くまべとそう）",
  },
  {
    key: "about.profile.table.2.th",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行2 見出し (代表)",
    kind: "text",
    maxLen: 10,
    defaultText: "代表",
  },
  {
    key: "about.profile.table.2.td",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行2 本文",
    kind: "text",
    maxLen: 14,
    defaultText: "隈部 信之",
  },
  {
    key: "about.profile.table.3.th",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行3 見出し (所在地)",
    kind: "text",
    maxLen: 10,
    defaultText: "所在地",
  },
  {
    key: "about.profile.table.3.td",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行3 本文",
    kind: "text",
    maxLen: 20,
    defaultText: "大分県豊後高田市",
  },
  {
    key: "about.profile.table.4.th",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行4 見出し (事業内容)",
    kind: "text",
    maxLen: 12,
    defaultText: "事業内容",
  },
  {
    key: "about.profile.table.4.td",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行4 本文",
    kind: "text",
    maxLen: 60,
    defaultText: "3Dプリント造形物の表面処理（研磨・塗装）／家電の量産塗装",
  },
  {
    key: "about.profile.table.5.th",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行5 見出し (対応エリア)",
    kind: "text",
    maxLen: 14,
    defaultText: "対応エリア",
  },
  {
    key: "about.profile.table.5.td",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行5 本文",
    kind: "text",
    maxLen: 70,
    defaultText: "全国（郵送受託）。主戦場は手のひら〜200×200mm級の小〜中型品。",
  },
  {
    key: "about.profile.table.6.th",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行6 見出し (受付窓口)",
    kind: "text",
    maxLen: 10,
    defaultText: "受付窓口",
  },
  {
    key: "about.profile.table.6.td",
    page: "about",
    route: "/about",
    label: "会社案内 / 会社概要表 行6 本文",
    kind: "text",
    maxLen: 40,
    defaultText: "準備中（先行のご相談は紹介経由で承っています）",
  },

  // ---- SEC.05 LOCATION ----
  {
    key: "about.location.sec.label",
    page: "about",
    route: "/about",
    label: "会社案内 / SEC.05 セクションラベル",
    kind: "text",
    maxLen: 16,
    defaultText: "LOCATION",
  },
  {
    key: "about.location.heading",
    page: "about",
    route: "/about",
    label: "会社案内 / LOCATION 見出し",
    kind: "text",
    maxLen: 20,
    defaultText: "大分県豊後高田市",
  },
  {
    key: "about.location.lead",
    page: "about",
    route: "/about",
    label: "会社案内 / LOCATION リード文 (SecLead内埋め込みのため text kind)",
    kind: "text",
    maxLen: 100,
    defaultText:
      "郵送受託が基本のため、地方立地のハンデはありません。送料が軽微な小〜中型品なら、全国どこからでも同じ条件でお受けできます。",
  },
  {
    key: "about.location.note",
    page: "about",
    route: "/about",
    label: "会社案内 / LOCATION 注記 (MapNote)",
    kind: "text",
    maxLen: 55,
    defaultText: "※ 工房の詳細な住所は、ご依頼確定時に発送先としてご案内します。",
  },

  // ---- GALLERY ----
  {
    key: "about.gallery.sec.label",
    page: "about",
    route: "/about",
    label: "会社案内 / GALLERY セクションラベル",
    kind: "text",
    maxLen: 18,
    defaultText: "THE PLACE",
  },
  {
    key: "about.gallery.lead",
    page: "about",
    route: "/about",
    label: "会社案内 / GALLERY リード文 (SecLead内埋め込みのため text kind)",
    kind: "text",
    maxLen: 55,
    defaultText: "大分・豊後高田の工房で、造形物と一個ずつ向き合っています。",
  },
  {
    key: "about.gallery.1.capja",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.04 (手の仕事写真) 日本語キャプション",
    kind: "text",
    maxLen: 12,
    defaultText: "手の仕事",
  },
  {
    key: "about.gallery.1.capen",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.04 (手の仕事写真) 英語キャプション",
    kind: "text",
    maxLen: 24,
    defaultText: "CRAFTSMANSHIP",
  },
  {
    key: "about.gallery.1.credit",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.04 (手の仕事写真) クレジット表記",
    kind: "text",
    maxLen: 40,
    defaultText: "Photo: riiyad / Unsplash",
  },
  {
    key: "about.gallery.2.capja",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.05 (質感写真) 日本語キャプション",
    kind: "text",
    maxLen: 12,
    defaultText: "面の質感",
  },
  {
    key: "about.gallery.2.capen",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.05 (質感写真) 英語キャプション",
    kind: "text",
    maxLen: 22,
    defaultText: "THE SURFACE",
  },
  {
    key: "about.gallery.2.credit",
    page: "about",
    route: "/about",
    label: "会社案内 / FIG.05 (質感写真) クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: apryan_cahyo / Unsplash",
  },

  // ---- CTA ----
  {
    key: "about.cta.button",
    page: "about",
    route: "/about",
    label: "会社案内 / CTA帯 ボタン文言",
    kind: "text",
    maxLen: 20,
    defaultText: "サービス・料金を見る",
  },
];
