import type { PageTextSlot } from "../types";

// ---------------------------------------------------------------------------
// colors (84, route: "/colors")
// v2 Wave 1 (docs/design/visual-text-editor-v2.md §5): 既存4件 (hero.heading/lead・
// cta.heading/note) はそのまま維持し、page-body.tsx の残り全静的テキストを追加。defaultText は
// 現行描画テキストと1文字も違わない (非退行)。swatch.N.title と swatch.N.en は page-body.tsx の
// JSX 上で別要素 (h2 直下テキスト / 入れ子 font-mono span) のため別フィールド = plain (rich にしない、
// shop.ts の capJa/capEn と同じ判断)。PhotoFigure の figNo は shop.ts 既存慣例と同じく対象外。
// ---------------------------------------------------------------------------
export const COLORS_TEXT_SLOTS: readonly PageTextSlot[] = [
  {
    key: "colors.hero.heading",
    page: "colors",
    route: "/colors",
    label: "色見本 / ヒーロー見出し (8枚 = SWATCHES.length と手動同期)",
    kind: "lines",
    maxLen: 36,
    defaultText: "名車の象徴色で組んだ、\n8枚の技術証明。",
    maxLines: 2,
    maxLineLen: 20,
  },
  {
    key: "colors.hero.lead",
    page: "colors",
    route: "/colors",
    label: "色見本 / ヒーローリード文 (8色中5色 = 手動同期)",
    kind: "multiline",
    maxLen: 200,
    defaultText:
      "見る人に一瞬で技術レベルを伝えるための、色見本ラインナップです。8色中5色が3コート・高難度系。いずれも市販の調色済み補修塗料を正規の用途で使用し、「参考色」として仕上げます。実物の色見本パネル（対辺70mmの六角形・裏面カラーコード刻印）は、郵送でお貸し出しできるよう準備中です。",
  },
  {
    key: "colors.cta.heading",
    page: "colors",
    route: "/colors",
    label: "色見本 / CTA帯 見出し",
    kind: "lines",
    maxLen: 44,
    defaultText: "この8色以外も、\n色番号でご指定いただけます。",
    maxLines: 2,
  },
  {
    key: "colors.cta.note",
    page: "colors",
    route: "/colors",
    label: "色見本 / CTA帯 補足",
    kind: "text",
    maxLen: 60,
    defaultText: "日塗工番号・自動車カラーコードに対応。まずはサイズ×個数×グレードでご相談ください。",
  },
  // --- ヒーロー PageHead 連番/英字ラベル (page-blocks.tsx PageHead index/en) ---
  {
    key: "colors.hero.index",
    page: "colors",
    route: "/colors",
    label: "色見本 / PageHead 連番表記 (INDEX NN — ページ名)",
    kind: "text",
    maxLen: 30,
    defaultText: "INDEX 07 — COLORS",
  },
  {
    key: "colors.hero.en",
    page: "colors",
    route: "/colors",
    label: "色見本 / PageHead 英字サブラベル (8色中5色 = 手動同期)",
    kind: "text",
    maxLen: 40,
    defaultText: "8 SWATCHES / 5 ARE 3-COAT",
  },

  // --- FIG.00〜03 PhotoFigure キャプション (figNo は非対象、shop.ts 既存慣例と同じ) ---
  {
    key: "colors.hero.photo.capja",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.00 (色見本ヒーロー写真) 日本語キャプション",
    kind: "text",
    maxLen: 40,
    defaultText: "名車の色は、塗る人の経験が発色させる。",
  },
  {
    key: "colors.hero.photo.capen",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.00 (色見本ヒーロー写真) 英語キャプション",
    kind: "text",
    maxLen: 40,
    defaultText: "COLOR AS PROOF OF SKILL",
  },
  {
    key: "colors.hero.photo.credit",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.00 (色見本ヒーロー写真) クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: aaronburden / Unsplash",
  },
  {
    key: "colors.band.1.capja",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.01 (黒の深さ) 日本語キャプション",
    kind: "text",
    maxLen: 40,
    defaultText: "黒の深さは、研ぎで決まる。",
  },
  {
    key: "colors.band.1.capen",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.01 (黒の深さ) 英語キャプション",
    kind: "text",
    maxLen: 40,
    defaultText: "DEPTH OF BLACK",
  },
  {
    key: "colors.band.1.credit",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.01 (黒の深さ) クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: cmreflections / Unsplash",
  },
  {
    key: "colors.band.2.capja",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.02 (光の映り込み) 日本語キャプション",
    kind: "text",
    maxLen: 40,
    defaultText: "光の映り込みが、平滑さを映す。",
  },
  {
    key: "colors.band.2.capen",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.02 (光の映り込み) 英語キャプション",
    kind: "text",
    maxLen: 40,
    defaultText: "REFLECTION",
  },
  {
    key: "colors.band.2.credit",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.02 (光の映り込み) クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: avenir_visuals / Unsplash",
  },
  {
    key: "colors.band.3.capja",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.03 (面の上の色) 日本語キャプション",
    kind: "text",
    maxLen: 40,
    defaultText: "色は、面の上に成立する。",
  },
  {
    key: "colors.band.3.capen",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.03 (面の上の色) 英語キャプション",
    kind: "text",
    maxLen: 40,
    defaultText: "ON THE SURFACE",
  },
  {
    key: "colors.band.3.credit",
    page: "colors",
    route: "/colors",
    label: "色見本 / FIG.03 (面の上の色) クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: apryan_cahyo / Unsplash",
  },

  // --- 8色の色見本エントリ (ColorEntry / Drawdown): index・title・英語コード・DRAWDOWN番号/バッジ名・specs バッジ・story文 ---
  // SWATCH 01 — プレシャスホワイトパール (c-090)
  {
    key: "colors.swatch.1.index",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 01 インデックス表記",
    kind: "text",
    maxLen: 15,
    defaultText: "SWATCH 01",
  },
  {
    key: "colors.swatch.1.title",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 01 色名見出し",
    kind: "text",
    maxLen: 40,
    defaultText: "プレシャスホワイトパール",
  },
  {
    key: "colors.swatch.1.en",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 01 英語カラーコード併記",
    kind: "text",
    maxLen: 60,
    defaultText: "TOYOTA 090 — PRECIOUS WHITE PEARL",
  },
  {
    key: "colors.swatch.1.dd.no",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 01 DRAWDOWN番号バッジ (8枚中の通し番号、swatch数と手動同期)",
    kind: "text",
    maxLen: 20,
    defaultText: "DRAWDOWN 01 / 8",
  },
  {
    key: "colors.swatch.1.dd.name",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 01 DRAWDOWNバッジ色名 (短縮表記、色名見出しとは別フィールド)",
    kind: "text",
    maxLen: 30,
    defaultText: "プレシャスホワイトパール",
  },
  {
    key: "colors.swatch.1.spec.1",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 01 specsバッジ1",
    kind: "text",
    maxLen: 20,
    defaultText: "3コートパール",
  },
  {
    key: "colors.swatch.1.spec.2",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 01 specsバッジ2",
    kind: "text",
    maxLen: 20,
    defaultText: "ベース＋パール＋クリア",
  },
  {
    key: "colors.swatch.1.spec.3",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 01 specsバッジ3",
    kind: "text",
    maxLen: 20,
    defaultText: "実績納品色",
  },
  {
    key: "colors.swatch.1.story",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 01 ストーリー文",
    kind: "text",
    maxLen: 160,
    defaultText: "現に法人のプロダクト試作へ納品している、この工房の実績色であり原点。白の奥でパールが回る上品な光は、単なる「白塗装」とはまったく別のものです。3コートの技術がそのまま出る、看板の一枚。",
  },

  // SWATCH 02 — ソウルレッドクリスタルメタリック (c-46v)
  {
    key: "colors.swatch.2.index",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 02 インデックス表記",
    kind: "text",
    maxLen: 15,
    defaultText: "SWATCH 02",
  },
  {
    key: "colors.swatch.2.title",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 02 色名見出し",
    kind: "text",
    maxLen: 40,
    defaultText: "ソウルレッドクリスタルメタリック",
  },
  {
    key: "colors.swatch.2.en",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 02 英語カラーコード併記",
    kind: "text",
    maxLen: 60,
    defaultText: "MAZDA 46V — SOUL RED CRYSTAL",
  },
  {
    key: "colors.swatch.2.dd.no",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 02 DRAWDOWN番号バッジ (8枚中の通し番号、swatch数と手動同期)",
    kind: "text",
    maxLen: 20,
    defaultText: "DRAWDOWN 02 / 8",
  },
  {
    key: "colors.swatch.2.dd.name",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 02 DRAWDOWNバッジ色名 (短縮表記、色名見出しとは別フィールド)",
    kind: "text",
    maxLen: 30,
    defaultText: "ソウルレッドクリスタル",
  },
  {
    key: "colors.swatch.2.spec.1",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 02 specsバッジ1",
    kind: "text",
    maxLen: 20,
    defaultText: "3コート",
  },
  {
    key: "colors.swatch.2.spec.2",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 02 specsバッジ2",
    kind: "text",
    maxLen: 20,
    defaultText: "高難度",
  },
  {
    key: "colors.swatch.2.spec.3",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 02 specsバッジ3",
    kind: "text",
    maxLen: 20,
    defaultText: "匠塗",
  },
  {
    key: "colors.swatch.2.story",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 02 ストーリー文",
    kind: "text",
    maxLen: 160,
    defaultText: "「ディーラーですら同色にならない」と業界で言われる高難度色。光を吸収するフレークを含む3層構造で、塗り重ねの経験がそのまま発色に出ます。これが塗れること自体が、技術の証明になる一枚です。",
  },

  // SWATCH 03 — プレシャスブロンズ (c-4y6)
  {
    key: "colors.swatch.3.index",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 03 インデックス表記",
    kind: "text",
    maxLen: 15,
    defaultText: "SWATCH 03",
  },
  {
    key: "colors.swatch.3.title",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 03 色名見出し",
    kind: "text",
    maxLen: 40,
    defaultText: "プレシャスブロンズ",
  },
  {
    key: "colors.swatch.3.en",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 03 英語カラーコード併記",
    kind: "text",
    maxLen: 60,
    defaultText: "TOYOTA 4Y6 — PRECIOUS BRONZE",
  },
  {
    key: "colors.swatch.3.dd.no",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 03 DRAWDOWN番号バッジ (8枚中の通し番号、swatch数と手動同期)",
    kind: "text",
    maxLen: 20,
    defaultText: "DRAWDOWN 03 / 8",
  },
  {
    key: "colors.swatch.3.dd.name",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 03 DRAWDOWNバッジ色名 (短縮表記、色名見出しとは別フィールド)",
    kind: "text",
    maxLen: 30,
    defaultText: "プレシャスブロンズ",
  },
  {
    key: "colors.swatch.3.spec.1",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 03 specsバッジ1",
    kind: "text",
    maxLen: 20,
    defaultText: "メタリック",
  },
  {
    key: "colors.swatch.3.story",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 03 ストーリー文",
    kind: "text",
    maxLen: 160,
    defaultText: "現行クラウンの上品なブラウン。落ち着いた製品筐体や、大人のプロダクトに映えるメタリックです。派手さではなく品位で選ばれる色は、仕上げの均一さがすべてを決めます。",
  },

  // SWATCH 04 — ピンクサファイア (c-3t4)
  {
    key: "colors.swatch.4.index",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 04 インデックス表記",
    kind: "text",
    maxLen: 15,
    defaultText: "SWATCH 04",
  },
  {
    key: "colors.swatch.4.title",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 04 色名見出し",
    kind: "text",
    maxLen: 40,
    defaultText: "ピンクサファイア",
  },
  {
    key: "colors.swatch.4.en",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 04 英語カラーコード併記",
    kind: "text",
    maxLen: 60,
    defaultText: "TOYOTA 3T4 — PINK SAPPHIRE",
  },
  {
    key: "colors.swatch.4.dd.no",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 04 DRAWDOWN番号バッジ (8枚中の通し番号、swatch数と手動同期)",
    kind: "text",
    maxLen: 20,
    defaultText: "DRAWDOWN 04 / 8",
  },
  {
    key: "colors.swatch.4.dd.name",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 04 DRAWDOWNバッジ色名 (短縮表記、色名見出しとは別フィールド)",
    kind: "text",
    maxLen: 30,
    defaultText: "ピンクサファイア",
  },
  {
    key: "colors.swatch.4.spec.1",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 04 specsバッジ1",
    kind: "text",
    maxLen: 20,
    defaultText: "3コート",
  },
  {
    key: "colors.swatch.4.spec.2",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 04 specsバッジ2",
    kind: "text",
    maxLen: 20,
    defaultText: "限定色",
  },
  {
    key: "colors.swatch.4.story",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 04 ストーリー文",
    kind: "text",
    maxLen: 160,
    defaultText: "全国650台限定「ReBORN PINK」のクラウンに採用された伝説色、通称モモタロウ。話題性と可愛げを両立し、プロダクトのカラーバリエーション展開でも強い引きを持つ一枚です。",
  },

  // SWATCH 05 — ブラック (c-202)
  {
    key: "colors.swatch.5.index",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 05 インデックス表記",
    kind: "text",
    maxLen: 15,
    defaultText: "SWATCH 05",
  },
  {
    key: "colors.swatch.5.title",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 05 色名見出し",
    kind: "text",
    maxLen: 40,
    defaultText: "ブラック",
  },
  {
    key: "colors.swatch.5.en",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 05 英語カラーコード併記",
    kind: "text",
    maxLen: 60,
    defaultText: "TOYOTA 202 — BLACK",
  },
  {
    key: "colors.swatch.5.dd.no",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 05 DRAWDOWN番号バッジ (8枚中の通し番号、swatch数と手動同期)",
    kind: "text",
    maxLen: 20,
    defaultText: "DRAWDOWN 05 / 8",
  },
  {
    key: "colors.swatch.5.dd.name",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 05 DRAWDOWNバッジ色名 (短縮表記、色名見出しとは別フィールド)",
    kind: "text",
    maxLen: 30,
    defaultText: "ブラック",
  },
  {
    key: "colors.swatch.5.spec.1",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 05 specsバッジ1",
    kind: "text",
    maxLen: 20,
    defaultText: "ソリッド＋クリア",
  },
  {
    key: "colors.swatch.5.spec.2",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 05 specsバッジ2",
    kind: "text",
    maxLen: 20,
    defaultText: "最難関カラー",
  },
  {
    key: "colors.swatch.5.story",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 05 ストーリー文",
    kind: "text",
    maxLen: 160,
    defaultText: "「最難関カラー」と呼ばれるソリッドの黒。メタリックやパールのような粒子の助けがなく、下地の平滑さと塗り肌がそのまま出ます。ごまかしが効かないからこそ、腕の見せ所。当工房が下地に時間を割く理由を、いちばん雄弁に語る色です。",
  },

  // SWATCH 06 — ベイサイドブルー (c-tv2)
  {
    key: "colors.swatch.6.index",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 06 インデックス表記",
    kind: "text",
    maxLen: 15,
    defaultText: "SWATCH 06",
  },
  {
    key: "colors.swatch.6.title",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 06 色名見出し",
    kind: "text",
    maxLen: 40,
    defaultText: "ベイサイドブルー",
  },
  {
    key: "colors.swatch.6.en",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 06 英語カラーコード併記",
    kind: "text",
    maxLen: 60,
    defaultText: "NISSAN TV2 — BAYSIDE BLUE",
  },
  {
    key: "colors.swatch.6.dd.no",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 06 DRAWDOWN番号バッジ (8枚中の通し番号、swatch数と手動同期)",
    kind: "text",
    maxLen: 20,
    defaultText: "DRAWDOWN 06 / 8",
  },
  {
    key: "colors.swatch.6.dd.name",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 06 DRAWDOWNバッジ色名 (短縮表記、色名見出しとは別フィールド)",
    kind: "text",
    maxLen: 30,
    defaultText: "ベイサイドブルー",
  },
  {
    key: "colors.swatch.6.spec.1",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 06 specsバッジ1",
    kind: "text",
    maxLen: 20,
    defaultText: "3コート",
  },
  {
    key: "colors.swatch.6.spec.2",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 06 specsバッジ2",
    kind: "text",
    maxLen: 20,
    defaultText: "R34 GT-R",
  },
  {
    key: "colors.swatch.6.story",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 06 ストーリー文",
    kind: "text",
    maxLen: 160,
    defaultText: "R34 GT-Rの代名詞色。この色の補修では「経験のある塗装工場を探すことが重要」と言われ続けてきた、3コート構造のブルーです。だからこそ、看板色の一枚にしています。",
  },

  // SWATCH 07 — レーシンググリーン (c-am)
  {
    key: "colors.swatch.7.index",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 07 インデックス表記",
    kind: "text",
    maxLen: 15,
    defaultText: "SWATCH 07",
  },
  {
    key: "colors.swatch.7.title",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 07 色名見出し",
    kind: "text",
    maxLen: 40,
    defaultText: "レーシンググリーン",
  },
  {
    key: "colors.swatch.7.en",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 07 英語カラーコード併記",
    kind: "text",
    maxLen: 60,
    defaultText: "ASTON MARTIN AM9539 — RACING GREEN",
  },
  {
    key: "colors.swatch.7.dd.no",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 07 DRAWDOWN番号バッジ (8枚中の通し番号、swatch数と手動同期)",
    kind: "text",
    maxLen: 20,
    defaultText: "DRAWDOWN 07 / 8",
  },
  {
    key: "colors.swatch.7.dd.name",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 07 DRAWDOWNバッジ色名 (短縮表記、色名見出しとは別フィールド)",
    kind: "text",
    maxLen: 30,
    defaultText: "レーシンググリーン",
  },
  {
    key: "colors.swatch.7.spec.1",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 07 specsバッジ1",
    kind: "text",
    maxLen: 20,
    defaultText: "メタリック",
  },
  {
    key: "colors.swatch.7.spec.2",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 07 specsバッジ2",
    kind: "text",
    maxLen: 20,
    defaultText: "英国の象徴色",
  },
  {
    key: "colors.swatch.7.story",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 07 ストーリー文",
    kind: "text",
    maxLen: 160,
    defaultText: "英国レーシングの伝統を背負う深緑。市販車とF1マシンが同じ塗料配合という、由緒ある色です。深みのある濃色メタリックは、光の当たり方で表情が変わる——その変化を均一に出すのが職人の仕事です。",
  },

  // SWATCH 08 — マシーングレープレミアムメタリック (c-46g)
  {
    key: "colors.swatch.8.index",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 08 インデックス表記",
    kind: "text",
    maxLen: 15,
    defaultText: "SWATCH 08",
  },
  {
    key: "colors.swatch.8.title",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 08 色名見出し",
    kind: "text",
    maxLen: 40,
    defaultText: "マシーングレープレミアムメタリック",
  },
  {
    key: "colors.swatch.8.en",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 08 英語カラーコード併記",
    kind: "text",
    maxLen: 60,
    defaultText: "MAZDA 46G — MACHINE GRAY",
  },
  {
    key: "colors.swatch.8.dd.no",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 08 DRAWDOWN番号バッジ (8枚中の通し番号、swatch数と手動同期)",
    kind: "text",
    maxLen: 20,
    defaultText: "DRAWDOWN 08 / 8",
  },
  {
    key: "colors.swatch.8.dd.name",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 08 DRAWDOWNバッジ色名 (短縮表記、色名見出しとは別フィールド)",
    kind: "text",
    maxLen: 30,
    defaultText: "マシーングレー",
  },
  {
    key: "colors.swatch.8.spec.1",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 08 specsバッジ1",
    kind: "text",
    maxLen: 20,
    defaultText: "高難度メタリック",
  },
  {
    key: "colors.swatch.8.spec.2",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 08 specsバッジ2",
    kind: "text",
    maxLen: 20,
    defaultText: "匠塗",
  },
  {
    key: "colors.swatch.8.story",
    page: "colors",
    route: "/colors",
    label: "色見本 / SWATCH 08 ストーリー文",
    kind: "text",
    maxLen: 160,
    defaultText: "46Vソウルレッドと並ぶ「匠塗」の2枚看板。金属の塊から削り出したような精緻な質感が特徴です。マツダの匠塗を両方仕上げられる工房——このラインナップが語る、技術ストーリーの完成形です。",
  },

  // --- 色見本ページ末尾の免責・対応範囲注記 (MapNote) ---
  {
    key: "colors.disclaimer",
    page: "colors",
    route: "/colors",
    label: "色見本 / 免責・対応範囲注記",
    kind: "text",
    maxLen: 150,
    defaultText: "※ 画面上の色はイメージです。日塗工番号・自動車カラーコードでの色番号指定に対応します。純正色のピタリ合わせ（調色）は対象外で、市販の調色済み補修塗料による「参考色」仕上げです。実在車の車体形状の複製は行いません。",
  },

];
