import type { PageTextSlot } from "../types";

// ---------------------------------------------------------------------------
// contact (2 + 71, route: "/contact")
// 既存2件 (hero.heading/hero.lead) はそのまま維持し、v2 Wave 1 でページ残り全静的テキスト
// (フォーム外 36件 + ContactForm/actions.ts の client 部品 35件) を追加。defaultText は
// 現行描画テキストと1文字も違わない (非退行)。ContactForm は "use client" のため
// data-editable-text を手動付与する方式で配線する (contact-form.tsx 側コメント参照)。
// rich は同意チェックボックスの1件のみ (contact.form.consent.text、link トークン)。
// ---------------------------------------------------------------------------
export const CONTACT_TEXT_SLOTS: readonly PageTextSlot[] = [
  {
    key: "contact.hero.heading",
    page: "contact",
    route: "/contact",
    label: "相談する / ヒーロー見出し",
    kind: "lines",
    maxLen: 20,
    defaultText: "見積もりは、\n3つの数字で。",
    maxLines: 2,
    maxLineLen: 20,
  },
  {
    key: "contact.hero.lead",
    page: "contact",
    route: "/contact",
    label: "相談する / ヒーローリード文",
    kind: "multiline",
    maxLen: 200,
    defaultText:
      "「サイズ × 個数 × グレード」がわかれば、概算をお出しできます。下地が全グレード共通だから、見積もりの構造もこれだけシンプルです。造形データや写真、素材の種類がわかると、より正確になります。",
  },

  // ---- ここから v2 Wave 1 追加 (フォーム外, page-body.tsx) ----
  {
    key: "contact.hero.index",
    page: "contact",
    route: "/contact",
    label: "相談する / PageHead 連番表記 (INDEX NN — ページ名)",
    kind: "text",
    maxLen: 30,
    defaultText: "INDEX 10 — CONTACT",
  },
  {
    key: "contact.hero.en",
    page: "contact",
    route: "/contact",
    label: "相談する / PageHead 英字サブ表記",
    kind: "text",
    maxLen: 30,
    defaultText: "SIZE × QTY × GRADE",
  },
  {
    key: "contact.hero.photo.capja",
    page: "contact",
    route: "/contact",
    label: "相談する / ヒーロー写真 和文キャプション",
    kind: "text",
    maxLen: 40,
    defaultText: "あなたの「絶対に外せない一個」を、この艶に。",
  },
  {
    key: "contact.hero.photo.capen",
    page: "contact",
    route: "/contact",
    label: "相談する / ヒーロー写真 英字キャプション",
    kind: "text",
    maxLen: 40,
    defaultText: "YOUR ONE PIECE, PERFECTED",
  },
  {
    key: "contact.hero.photo.credit",
    page: "contact",
    route: "/contact",
    label: "相談する / ヒーロー写真クレジット",
    kind: "text",
    maxLen: 50,
    defaultText: "Photo: aaronburden / Unsplash",
  },
  {
    key: "contact.sec.1.label",
    page: "contact",
    route: "/contact",
    label: "相談する / SEC.01 セクションラベル",
    kind: "text",
    maxLen: 30,
    defaultText: "HOW TO ESTIMATE",
  },
  {
    key: "contact.quotevar.1.label",
    page: "contact",
    route: "/contact",
    label: "相談する / 3変数カード1 英字ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "SIZE",
  },
  {
    key: "contact.quotevar.1.ja",
    page: "contact",
    route: "/contact",
    label: "相談する / 3変数カード1 和名",
    kind: "text",
    maxLen: 10,
    defaultText: "サイズ",
  },
  {
    key: "contact.quotevar.1.body",
    page: "contact",
    route: "/contact",
    label: "相談する / 3変数カード1 本文",
    kind: "text",
    maxLen: 120,
    defaultText:
      "最長辺のおおよその寸法をお知らせください。主戦場は手のひら〜200×200mm級。大型は個別見積もり（送料実費）で対応します。",
  },
  {
    key: "contact.quotevar.2.label",
    page: "contact",
    route: "/contact",
    label: "相談する / 3変数カード2 英字ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "QTY",
  },
  {
    key: "contact.quotevar.2.ja",
    page: "contact",
    route: "/contact",
    label: "相談する / 3変数カード2 和名",
    kind: "text",
    maxLen: 10,
    defaultText: "個数",
  },
  {
    key: "contact.quotevar.2.body",
    page: "contact",
    route: "/contact",
    label: "相談する / 3変数カード2 本文",
    kind: "text",
    maxLen: 110,
    defaultText:
      "1点から1,000個まで。同一品は10個以上で−15%、30個以上で−25%（目安）の数量スライドが効きます。",
  },
  {
    key: "contact.quotevar.3.label",
    page: "contact",
    route: "/contact",
    label: "相談する / 3変数カード3 英字ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "GRADE",
  },
  {
    key: "contact.quotevar.3.ja",
    page: "contact",
    route: "/contact",
    label: "相談する / 3変数カード3 和名",
    kind: "text",
    maxLen: 10,
    defaultText: "グレード",
  },
  {
    key: "contact.quotevar.3.body",
    page: "contact",
    route: "/contact",
    label: "相談する / 3変数カード3 本文",
    kind: "text",
    maxLen: 110,
    defaultText:
      "下地仕上げ / スタンダード / プレミアム（3コートパール）の3択。迷ったら用途をお聞かせください。ご提案します。",
  },
  {
    key: "contact.estimate.note",
    page: "contact",
    route: "/contact",
    label: "相談する / 3変数セクション 補足 (MapNote)",
    kind: "text",
    maxLen: 160,
    defaultText:
      "※ あわせて伝えていただけると正確になる情報 — 造形方式（FDM / 光造形など）、素材の種類、希望色（カラーコード可）、希望納期。未経験の素材はテストピース確認を挟みます。NDA対応可。",
  },
  {
    key: "contact.sec.2.label",
    page: "contact",
    route: "/contact",
    label: "相談する / SEC.02 セクションラベル",
    kind: "text",
    maxLen: 30,
    defaultText: "CONTACT FORM",
  },
  {
    key: "contact.form.heading",
    page: "contact",
    route: "/contact",
    label: "相談する / お問い合わせフォーム 見出し",
    kind: "text",
    maxLen: 20,
    defaultText: "お問い合わせフォーム",
  },
  {
    key: "contact.form.lead",
    page: "contact",
    route: "/contact",
    label: "相談する / お問い合わせフォーム リード文",
    kind: "text",
    maxLen: 90,
    defaultText: "下記フォームからお問い合わせいただけます。内容を確認のうえ、担当より折り返しご連絡いたします。",
  },
  {
    key: "contact.sec.3.label",
    page: "contact",
    route: "/contact",
    label: "相談する / SEC.03 セクションラベル",
    kind: "text",
    maxLen: 30,
    defaultText: "BEFORE YOU ASK",
  },
  {
    key: "contact.before.heading",
    page: "contact",
    route: "/contact",
    label: "相談する / 逆リンク 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "ご相談の前に。",
  },
  {
    key: "contact.before.lead",
    page: "contact",
    route: "/contact",
    label: "相談する / 逆リンク リード文",
    kind: "text",
    maxLen: 150,
    defaultText:
      "工程・グレード・数量スライドの詳細はサービスページに、対応色の考え方は色見本ページにまとめています。「できないこと」も先に書いています——正直さも品質のうちです。",
  },
  {
    key: "contact.before.link.service",
    page: "contact",
    route: "/contact",
    label: "相談する / 逆リンクボタン (サービス・料金)",
    kind: "text",
    maxLen: 16,
    defaultText: "サービス・料金",
  },
  {
    key: "contact.before.link.colors",
    page: "contact",
    route: "/contact",
    label: "相談する / 逆リンクボタン (色見本)",
    kind: "text",
    maxLen: 10,
    defaultText: "色見本",
  },
  {
    key: "contact.sec.4.label",
    page: "contact",
    route: "/contact",
    label: "相談する / SEC.04 セクションラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "FAQ",
  },
  {
    key: "contact.faq.heading",
    page: "contact",
    route: "/contact",
    label: "相談する / FAQ 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "よくあるご質問",
  },
  {
    key: "contact.faq.q.1",
    page: "contact",
    route: "/contact",
    label: "相談する / FAQ Q1",
    kind: "text",
    maxLen: 30,
    defaultText: "造形データだけでも頼めますか？",
  },
  {
    key: "contact.faq.a.1",
    page: "contact",
    route: "/contact",
    label: "相談する / FAQ A1",
    kind: "text",
    maxLen: 200,
    defaultText:
      "はい。データ入稿 → 提携出力 → 工房直送の流れに対応しています。造形から仕上げまで一括でお受けできるため、「出力先と塗装先を別々に手配する」手間が省けます。造形方式（FDM / 光造形など）のご希望があればお知らせください。",
  },
  {
    key: "contact.faq.q.2",
    page: "contact",
    route: "/contact",
    label: "相談する / FAQ Q2",
    kind: "text",
    maxLen: 30,
    defaultText: "色は完全に純正色と同じにできますか？",
  },
  {
    key: "contact.faq.a.2",
    page: "contact",
    route: "/contact",
    label: "相談する / FAQ A2",
    kind: "text",
    maxLen: 200,
    defaultText:
      "純正色のピタリ合わせ（調色）は対象外です。市販の調色済み補修塗料を正規の用途で使い、「参考色」として仕上げます。日塗工番号・自動車カラーコードでのご指定には対応します。8色ラインナップ以外の色もご相談ください。",
  },
  {
    key: "contact.faq.q.3",
    page: "contact",
    route: "/contact",
    label: "相談する / FAQ Q3",
    kind: "text",
    maxLen: 30,
    defaultText: "どのくらいの納期ですか？",
  },
  {
    key: "contact.faq.a.3",
    page: "contact",
    route: "/contact",
    label: "相談する / FAQ A3",
    kind: "text",
    maxLen: 200,
    defaultText:
      "2液ウレタンの完全硬化に5〜7日かかり、硬化を確認してから発送します。工程日数を加えた目安は個別にお出しします。特急仕上げ（+50%）も可能です。繁忙期は品質維持のため「納期◯週間待ち」を表示して受注を絞ることがあります。",
  },
  {
    key: "contact.faq.q.4",
    page: "contact",
    route: "/contact",
    label: "相談する / FAQ Q4",
    kind: "text",
    maxLen: 30,
    defaultText: "初めての素材でも塗ってもらえますか？",
  },
  {
    key: "contact.faq.a.4",
    page: "contact",
    route: "/contact",
    label: "相談する / FAQ A4",
    kind: "text",
    maxLen: 160,
    defaultText:
      "経験のない樹脂素材は、いきなり本番にはせず、テストピースで相性を確認してから進めます。塗料の食いつきや溶剤の影響を事前に見極めるためで、結果的に失敗のリスクを下げられます。",
  },
  {
    key: "contact.faq.q.5",
    page: "contact",
    route: "/contact",
    label: "相談する / FAQ Q5",
    kind: "text",
    maxLen: 30,
    defaultText: "秘密保持（NDA）に対応できますか？",
  },
  {
    key: "contact.faq.a.5",
    page: "contact",
    route: "/contact",
    label: "相談する / FAQ A5",
    kind: "text",
    maxLen: 160,
    defaultText:
      "対応可能です。進行中の写真は守秘義務の範囲で管理し、実績としての掲載は案件ごとに許諾をいただいてからにしています。未発表製品の試作でも安心してお預けください。",
  },

  // ---- ここから v2 Wave 1 追加 (ContactForm / actions.ts, "use client" のため
  //      手動 data-editable-text パターンで配線する。contact-form.tsx コメント参照) ----
  {
    key: "contact.form.badge.form",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム STATUS バッジ (未送信)",
    kind: "text",
    maxLen: 30,
    defaultText: "STATUS — CONTACT FORM",
  },
  {
    key: "contact.form.badge.received",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム STATUS バッジ (送信済み)",
    kind: "text",
    maxLen: 30,
    defaultText: "STATUS — RECEIVED",
  },
  {
    key: "contact.form.intro",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム 冒頭案内文",
    kind: "text",
    maxLen: 80,
    defaultText: "必要事項をご入力のうえ送信してください。内容を確認し、担当より折り返しご連絡いたします。",
  },
  {
    key: "contact.form.success.message",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム送信完了メッセージ",
    kind: "text",
    maxLen: 60,
    defaultText: "お問い合わせを受け付けました。内容を確認のうえ、ご連絡いたします。",
  },
  {
    key: "contact.form.button.reset",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「もう一度入力する」ボタン",
    kind: "text",
    maxLen: 20,
    defaultText: "もう一度入力する",
  },
  {
    key: "contact.form.label.name",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「お名前」ラベル (必須マークは構造で別途保持)",
    kind: "text",
    maxLen: 10,
    defaultText: "お名前",
  },
  {
    key: "contact.form.placeholder.name",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「お名前」placeholder",
    kind: "text",
    maxLen: 20,
    defaultText: "山田 太郎",
  },
  {
    key: "contact.form.label.email",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「メールアドレス」ラベル (必須マークは構造で別途保持)",
    kind: "text",
    maxLen: 16,
    defaultText: "メールアドレス",
  },
  {
    key: "contact.form.placeholder.email",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「メールアドレス」placeholder",
    kind: "text",
    maxLen: 30,
    defaultText: "you@example.com",
  },
  {
    key: "contact.form.label.phone",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「電話番号(任意)」ラベル",
    kind: "text",
    maxLen: 16,
    defaultText: "電話番号(任意)",
  },
  {
    key: "contact.form.placeholder.phone",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「電話番号」placeholder",
    kind: "text",
    maxLen: 30,
    defaultText: "090-1234-5678",
  },
  {
    key: "contact.form.label.inquiryType",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「お問い合わせ種別」ラベル (必須マークは構造で別途保持)",
    kind: "text",
    maxLen: 16,
    defaultText: "お問い合わせ種別",
  },
  {
    key: "contact.form.placeholder.inquiryType",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「お問い合わせ種別」placeholder",
    kind: "text",
    maxLen: 20,
    defaultText: "選択してください",
  },
  {
    key: "contact.form.option.construction",
    page: "contact",
    route: "/contact",
    label: "相談する / お問い合わせ種別 選択肢「施工依頼」",
    kind: "text",
    maxLen: 16,
    defaultText: "施工依頼",
  },
  {
    key: "contact.form.option.estimate",
    page: "contact",
    route: "/contact",
    label: "相談する / お問い合わせ種別 選択肢「見積もり相談」",
    kind: "text",
    maxLen: 16,
    defaultText: "見積もり相談",
  },
  {
    key: "contact.form.option.material",
    page: "contact",
    route: "/contact",
    label: "相談する / お問い合わせ種別 選択肢「材料に関する質問」",
    kind: "text",
    maxLen: 20,
    defaultText: "材料に関する質問",
  },
  {
    key: "contact.form.option.other",
    page: "contact",
    route: "/contact",
    label: "相談する / お問い合わせ種別 選択肢「その他」",
    kind: "text",
    maxLen: 10,
    defaultText: "その他",
  },
  {
    key: "contact.form.label.targetItem",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「対象品目(任意)」ラベル",
    kind: "text",
    maxLen: 16,
    defaultText: "対象品目(任意)",
  },
  {
    key: "contact.form.placeholder.targetItem",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「対象品目」placeholder",
    kind: "text",
    maxLen: 40,
    defaultText: "例: スマホケース、車両パーツ など",
  },
  {
    key: "contact.form.label.message",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「内容」ラベル (必須マークは構造で別途保持)",
    kind: "text",
    maxLen: 10,
    defaultText: "内容",
  },
  {
    key: "contact.form.placeholder.message",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「内容」placeholder",
    kind: "text",
    maxLen: 80,
    defaultText: "ご相談内容、サイズ・個数・希望グレード、造形データの有無などをご記入ください。",
  },
  {
    key: "contact.form.description.message",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム「内容」欄の補足説明",
    kind: "text",
    maxLen: 40,
    defaultText: "10文字以上5000文字以内でご記入ください。",
  },
  {
    key: "contact.form.consent.text",
    page: "contact",
    route: "/contact",
    label: "相談する / 同意チェックボックス文言 (プライバシーポリシーへのリンク込み。末尾 `*` は構造で別途保持)",
    kind: "rich",
    maxLen: 60,
    defaultText: "[プライバシーポリシー](/privacy)に同意する",
  },
  {
    key: "contact.form.button.submit",
    page: "contact",
    route: "/contact",
    label: "相談する / フォーム送信ボタン",
    kind: "text",
    maxLen: 16,
    defaultText: "送信する",
  },
  {
    key: "contact.form.error.name",
    page: "contact",
    route: "/contact",
    label: "相談する / エラー文言「お名前」未入力",
    kind: "text",
    maxLen: 40,
    defaultText: "お名前を入力してください",
  },
  {
    key: "contact.form.error.email",
    page: "contact",
    route: "/contact",
    label: "相談する / エラー文言「メールアドレス」不正",
    kind: "text",
    maxLen: 40,
    defaultText: "正しいメールアドレスを入力してください",
  },
  {
    key: "contact.form.error.phone",
    page: "contact",
    route: "/contact",
    label: "相談する / エラー文言「電話番号」不正",
    kind: "text",
    maxLen: 40,
    defaultText: "正しい電話番号の形式で入力してください",
  },
  {
    key: "contact.form.error.inquiryType",
    page: "contact",
    route: "/contact",
    label: "相談する / エラー文言「お問い合わせ種別」未選択",
    kind: "text",
    maxLen: 40,
    defaultText: "お問い合わせ種別を選択してください",
  },
  {
    key: "contact.form.error.targetItem",
    page: "contact",
    route: "/contact",
    label: "相談する / エラー文言「対象品目」文字数超過",
    kind: "text",
    maxLen: 40,
    defaultText: "100文字以内でご記入ください",
  },
  {
    key: "contact.form.error.message.min",
    page: "contact",
    route: "/contact",
    label: "相談する / エラー文言「内容」下限未満",
    kind: "text",
    maxLen: 40,
    defaultText: "内容は10文字以上でご記入ください",
  },
  {
    key: "contact.form.error.message.max",
    page: "contact",
    route: "/contact",
    label: "相談する / エラー文言「内容」上限超過",
    kind: "text",
    maxLen: 40,
    defaultText: "内容は5000文字以内でご記入ください",
  },
  {
    key: "contact.form.error.agree",
    page: "contact",
    route: "/contact",
    label: "相談する / エラー文言「同意チェック」未チェック",
    kind: "text",
    maxLen: 40,
    defaultText: "プライバシーポリシーへの同意が必要です",
  },
  {
    key: "contact.form.error.invalid",
    page: "contact",
    route: "/contact",
    label: "相談する / エラー文言 (サーバ側 契約検証失敗、actions.ts)",
    kind: "text",
    maxLen: 40,
    defaultText: "入力内容をご確認ください。",
  },
  {
    key: "contact.form.error.rateLimited",
    page: "contact",
    route: "/contact",
    label: "相談する / エラー文言 (送信回数上限)",
    kind: "text",
    maxLen: 60,
    defaultText: "送信回数の上限に達しました。しばらく時間をおいてから再度お試しください。",
  },
  {
    key: "contact.form.error.generic",
    page: "contact",
    route: "/contact",
    label: "相談する / エラー文言 (汎用送信失敗)",
    kind: "text",
    maxLen: 50,
    defaultText: "送信に失敗しました。しばらくしてから再度お試しください。",
  },
];
