import type { PageTextSlot } from "../types";

// ---------------------------------------------------------------------------
// home (120, route: "/")
// v2 Wave 1: 既存15件はそのまま維持し、page-body.tsx の残り全静的テキストを追加。
// defaultText は現行描画テキストと1文字も違わない (非退行)。
// PhotoFigure 相当の figNo (FIG.00〜FIG.06) と SectionMark の no ("SEC. 01" 等 / "GALLERY")
// は shop.ts 確立の precedent (構造的な連番マーカー、data-sec-no 等の技術用途と同系統) に倣い
// 対象外。TICKER_ITEMS (aria-hidden マーキー) も対象外。STAT_GRID の num/display は
// StatCount 用の数値データであり、仕様上 unit/label/en/note の4フィールドのみを対象とする
// (unit が空文字の2項目は編集対象になり得ないため unitSlotKey を持たない)。
// TWO_SCENES の range もこれと同型の数値表示のため対象外。
// ---------------------------------------------------------------------------
export const HOME_TEXT_SLOTS: readonly PageTextSlot[] = [
  {
    key: "home.statement.heading",
    page: "home",
    route: "/",
    label: "トップ / STATEMENT 見出し",
    kind: "lines",
    maxLen: 90,
    defaultText:
      "デザインモデルの品質は、\n表面処理で決まる。\nそれでも、表面処理を高い水準で\n内製できる会社は、多くない。\nその空白のために、この工房がある。",
    maxLines: 5,
    maxLineLen: 18,
  },
  {
    key: "home.craft.heading",
    page: "home",
    route: "/",
    label: "トップ / CRAFT 見出し",
    kind: "text",
    maxLen: 24,
    defaultText: "3つの技術を、ひとりで持つ。",
  },
  {
    key: "home.craft.card.1.title",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード1 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "積層痕を消す研磨",
  },
  {
    key: "home.craft.card.2.title",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード2 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "自動車グレードの艶",
  },
  {
    key: "home.craft.card.3.title",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード3 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "3コートパールの意匠",
  },
  {
    key: "home.colorlineup.heading",
    page: "home",
    route: "/",
    label: "トップ / COLOR LINEUP 見出し",
    kind: "lines",
    maxLen: 30,
    defaultText: "名車の象徴色で組んだ、\n8枚の技術証明。",
    maxLines: 2,
  },
  {
    key: "home.twoscenes.heading",
    page: "home",
    route: "/",
    label: "トップ / TWO SCENES 見出し",
    kind: "text",
    maxLen: 26,
    defaultText: "一点の勝負にも、千個の生産にも。",
  },
  {
    key: "home.twoscenes.scene.1.title",
    page: "home",
    route: "/",
    label: "トップ / TWO SCENES シーン1 見出し",
    kind: "text",
    maxLen: 28,
    defaultText: "プレミアムデザインモデルの一点仕上げ",
  },
  {
    key: "home.twoscenes.scene.2.title",
    page: "home",
    route: "/",
    label: "トップ / TWO SCENES シーン2 見出し",
    kind: "text",
    maxLen: 28,
    defaultText: "金型を作らない少量生産の外観仕上げ",
  },
  {
    key: "home.stats.heading",
    page: "home",
    route: "/",
    label: "トップ / BY THE NUMBERS 見出し",
    kind: "lines",
    maxLen: 20,
    defaultText: "工房の能力を、\n数字で。",
    maxLines: 2,
  },
  {
    key: "home.materials.heading",
    page: "home",
    route: "/",
    label: "トップ / MATERIALS 導線見出し",
    kind: "lines",
    maxLen: 40,
    defaultText: "FDMも、光造形も、SLSも。\n素材ごとに、手を変える。",
    maxLines: 2,
  },
  {
    key: "home.notes.heading",
    page: "home",
    route: "/",
    label: "トップ / NOTES 導線見出し",
    kind: "lines",
    maxLen: 32,
    defaultText: "なぜ綺麗なのかは、\n写真だけでは伝わらない。",
    maxLines: 2,
  },
  {
    key: "home.gallery.heading",
    page: "home",
    route: "/",
    label: "トップ / GALLERY 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "工房の、手の記録。",
  },
  {
    key: "home.cta.heading",
    page: "home",
    route: "/",
    label: "トップ / CTA帯 見出し",
    kind: "lines",
    maxLen: 44,
    defaultText: "見積もりは、3つの数字で。\nサイズ × 個数 × グレード。",
    maxLines: 2,
  },
  {
    key: "home.cta.note",
    page: "home",
    route: "/",
    label: "トップ / CTA帯 補足",
    kind: "text",
    maxLen: 60,
    defaultText: "造形データや写真があれば、より正確に概算をお出しできます。",
  },

  // -- HERO --------------------------------------------------------------
  {
    key: "home.hero.index",
    page: "home",
    route: "/",
    label: "トップ / ヒーロー連番表記 (INDEX NN — ページ名)",
    kind: "text",
    maxLen: 25,
    defaultText: "INDEX 00 — HOME",
  },
  {
    key: "home.hero.en",
    page: "home",
    route: "/",
    label: "トップ / ヒーロー英字サブラベル",
    kind: "text",
    maxLen: 45,
    defaultText: "SURFACE FINISHING FOR 3D PRINTS",
  },
  {
    key: "home.hero.heading",
    page: "home",
    route: "/",
    label: "トップ / ヒーロー見出し (2行目の一語のみ kt-paint-mark 装飾)",
    kind: "lines",
    maxLen: 40,
    defaultText: "3Dプリントを、\n量産品と見分けがつかない\n外観に。",
    maxLines: 3,
    maxLineLen: 16,
  },
  {
    key: "home.hero.lead",
    page: "home",
    route: "/",
    label: "トップ / ヒーローリード文",
    kind: "text",
    maxLen: 110,
    defaultText:
      "積層痕を消す研磨から、自動車グレードの塗装仕上げまで。家電の量産塗装で「量産の精度」を磨いた自動車塗装職人が、勝負試作の一点からブリッジ生産の千個まで、郵送で全国からお受けします。",
  },
  {
    key: "home.hero.cta.1",
    page: "home",
    route: "/",
    label: "トップ / ヒーローボタン1 (SHOP導線)",
    kind: "text",
    maxLen: 20,
    defaultText: "SHOPで概算を出す",
  },
  {
    key: "home.hero.cta.2",
    page: "home",
    route: "/",
    label: "トップ / ヒーローボタン2 (COLORS導線)",
    kind: "text",
    maxLen: 20,
    defaultText: "8色の色見本を見る",
  },
  {
    key: "home.hero.cta.3",
    page: "home",
    route: "/",
    label: "トップ / ヒーローボタン3 (SERVICE導線)",
    kind: "text",
    maxLen: 16,
    defaultText: "サービス・料金",
  },

  // -- HERO PHOTO BAND -----------------------------------------------------
  {
    key: "home.hero.photo.capja",
    page: "home",
    route: "/",
    label: "トップ / FIG.00 (ヒーロー写真) 日本語キャプション",
    kind: "text",
    maxLen: 40,
    defaultText: "自動車グレードの塗装が、造形物の最終工程になる。",
  },
  {
    key: "home.hero.photo.capen",
    page: "home",
    route: "/",
    label: "トップ / FIG.00 (ヒーロー写真) 英語キャプション",
    kind: "text",
    maxLen: 35,
    defaultText: "AUTOMOTIVE-GRADE FINISH",
  },
  {
    key: "home.hero.photo.credit",
    page: "home",
    route: "/",
    label: "トップ / FIG.00 (ヒーロー写真) クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: cmreflections / Unsplash",
  },

  // -- STATEMENT -----------------------------------------------------------
  {
    key: "home.statement.label",
    page: "home",
    route: "/",
    label: "トップ / SEC.01 セクションラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "STATEMENT",
  },
  {
    key: "home.statement.body",
    page: "home",
    route: "/",
    label: "トップ / STATEMENT 本文",
    kind: "text",
    maxLen: 130,
    defaultText:
      "塗装はできても積層痕を知らない塗装店。造形はできても、仕上げは単色止まりの出力サービス。金型を作らない少量生産の最大の弱点は「積層痕のある外観」——それを解決する最終工程こそが、この市場の付加価値の在り処です。",
  },
  {
    key: "home.statement.cta",
    page: "home",
    route: "/",
    label: "トップ / STATEMENT ボタン (STORY導線)",
    kind: "text",
    maxLen: 20,
    defaultText: "なぜこの工房を始めたのか",
  },

  // -- CRAFT -----------------------------------------------------------------
  {
    key: "home.craft.label",
    page: "home",
    route: "/",
    label: "トップ / SEC.02 セクションラベル",
    kind: "text",
    maxLen: 16,
    defaultText: "CRAFT",
  },
  {
    key: "home.craft.card.1.no",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード1 連番バッジ",
    kind: "text",
    maxLen: 16,
    defaultText: "CRAFT 01",
  },
  {
    key: "home.craft.card.2.no",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード2 連番バッジ",
    kind: "text",
    maxLen: 16,
    defaultText: "CRAFT 02",
  },
  {
    key: "home.craft.card.3.no",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード3 連番バッジ",
    kind: "text",
    maxLen: 16,
    defaultText: "CRAFT 03",
  },
  {
    key: "home.craft.card.1.body",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード1 本文",
    kind: "text",
    maxLen: 85,
    defaultText:
      "3Dプリント特有の縞を #800 まで面で研ぎ落とし、プラサフで埋め、#1200 で仕上げる。塗装の出来の大半は、この下地で決まります。",
  },
  {
    key: "home.craft.card.2.body",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード2 本文",
    kind: "text",
    maxLen: 85,
    defaultText:
      "2液ウレタンクリアは、吹きっぱなしで自動車外板と同等の艶が出ます。鏡面磨きに時間を使わないから、品質を揺らさずに数を仕上げられます。",
  },
  {
    key: "home.craft.card.3.body",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード3 本文",
    kind: "text",
    maxLen: 75,
    defaultText:
      "ベース＋パール＋クリアの3層構造。ホワイトパールやソウルレッドなど、経験がそのまま出る高難度の意匠塗装に対応します。",
  },
  {
    key: "home.craft.cta.1",
    page: "home",
    route: "/",
    label: "トップ / CRAFT ボタン1 (PROCESS導線)",
    kind: "text",
    maxLen: 16,
    defaultText: "全9工程を見る",
  },
  {
    key: "home.craft.cta.2",
    page: "home",
    route: "/",
    label: "トップ / CRAFT ボタン2 (ABOUT導線)",
    kind: "text",
    maxLen: 20,
    defaultText: "工房と職人について",
  },
  {
    key: "home.craft.1.capja",
    page: "home",
    route: "/",
    label: "トップ / FIG.01 (CRAFT写真1) 日本語キャプション",
    kind: "text",
    maxLen: 16,
    defaultText: "研ぎの手",
  },
  {
    key: "home.craft.1.capen",
    page: "home",
    route: "/",
    label: "トップ / FIG.01 (CRAFT写真1) 英語キャプション",
    kind: "text",
    maxLen: 25,
    defaultText: "SANDING & PREP",
  },
  {
    key: "home.craft.1.credit",
    page: "home",
    route: "/",
    label: "トップ / FIG.01 (CRAFT写真1) クレジット表記",
    kind: "text",
    maxLen: 40,
    defaultText: "Photo: mazinomron / Unsplash",
  },
  {
    key: "home.craft.2.capja",
    page: "home",
    route: "/",
    label: "トップ / FIG.02 (CRAFT写真2) 日本語キャプション",
    kind: "text",
    maxLen: 16,
    defaultText: "吹き付けの手",
  },
  {
    key: "home.craft.2.capen",
    page: "home",
    route: "/",
    label: "トップ / FIG.02 (CRAFT写真2) 英語キャプション",
    kind: "text",
    maxLen: 28,
    defaultText: "SPRAY APPLICATION",
  },
  {
    key: "home.craft.2.credit",
    page: "home",
    route: "/",
    label: "トップ / FIG.02 (CRAFT写真2) クレジット表記",
    kind: "text",
    maxLen: 40,
    defaultText: "Photo: createasea / Unsplash",
  },
  {
    key: "home.craft.3.capja",
    page: "home",
    route: "/",
    label: "トップ / FIG.03 (CRAFT写真3) 日本語キャプション",
    kind: "text",
    maxLen: 16,
    defaultText: "仕上がりの艶",
  },
  {
    key: "home.craft.3.capen",
    page: "home",
    route: "/",
    label: "トップ / FIG.03 (CRAFT写真3) 英語キャプション",
    kind: "text",
    maxLen: 20,
    defaultText: "THE FINISH",
  },
  {
    key: "home.craft.3.credit",
    page: "home",
    route: "/",
    label: "トップ / FIG.03 (CRAFT写真3) クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: avenir_visuals / Unsplash",
  },

  // -- COLOR LINEUP ----------------------------------------------------------
  {
    key: "home.colorlineup.label",
    page: "home",
    route: "/",
    label: "トップ / SEC.03 セクションラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "COLOR LINEUP",
  },
  {
    key: "home.colorlineup.lead",
    page: "home",
    route: "/",
    label: "トップ / COLOR LINEUP リード文",
    kind: "text",
    maxLen: 75,
    defaultText:
      "8色中5色が3コート・高難度系。いずれも市販の調色済み補修塗料を正規の用途で使用し、「参考色」として仕上げます。",
  },
  {
    key: "home.colorlineup.swatch.1.code",
    page: "home",
    route: "/",
    label: "トップ / 色見本1 型式コード",
    kind: "text",
    maxLen: 30,
    defaultText: "TOYOTA 090 / 3COAT",
  },
  {
    key: "home.colorlineup.swatch.1.name",
    page: "home",
    route: "/",
    label: "トップ / 色見本1 色名",
    kind: "text",
    maxLen: 20,
    defaultText: "プレシャスホワイトパール",
  },
  {
    key: "home.colorlineup.swatch.1.note",
    page: "home",
    route: "/",
    label: "トップ / 色見本1 注記バッジ",
    kind: "text",
    maxLen: 20,
    defaultText: "実績納品色",
  },
  {
    key: "home.colorlineup.swatch.2.code",
    page: "home",
    route: "/",
    label: "トップ / 色見本2 型式コード",
    kind: "text",
    maxLen: 30,
    defaultText: "MAZDA 46V / 3COAT",
  },
  {
    key: "home.colorlineup.swatch.2.name",
    page: "home",
    route: "/",
    label: "トップ / 色見本2 色名",
    kind: "text",
    maxLen: 20,
    defaultText: "ソウルレッドクリスタル",
  },
  {
    key: "home.colorlineup.swatch.2.note",
    page: "home",
    route: "/",
    label: "トップ / 色見本2 注記バッジ",
    kind: "text",
    maxLen: 20,
    defaultText: "最高難度の技術証明",
  },
  {
    key: "home.colorlineup.swatch.3.code",
    page: "home",
    route: "/",
    label: "トップ / 色見本3 型式コード",
    kind: "text",
    maxLen: 30,
    defaultText: "TOYOTA 4Y6 / METALLIC",
  },
  {
    key: "home.colorlineup.swatch.3.name",
    page: "home",
    route: "/",
    label: "トップ / 色見本3 色名",
    kind: "text",
    maxLen: 20,
    defaultText: "プレシャスブロンズ",
  },
  {
    key: "home.colorlineup.swatch.3.note",
    page: "home",
    route: "/",
    label: "トップ / 色見本3 注記バッジ",
    kind: "text",
    maxLen: 20,
    defaultText: "現行クラウンの上品な茶",
  },
  {
    key: "home.colorlineup.swatch.4.code",
    page: "home",
    route: "/",
    label: "トップ / 色見本4 型式コード",
    kind: "text",
    maxLen: 30,
    defaultText: "TOYOTA 3T4 / 3COAT",
  },
  {
    key: "home.colorlineup.swatch.4.name",
    page: "home",
    route: "/",
    label: "トップ / 色見本4 色名",
    kind: "text",
    maxLen: 20,
    defaultText: "ピンクサファイア",
  },
  {
    key: "home.colorlineup.swatch.4.note",
    page: "home",
    route: "/",
    label: "トップ / 色見本4 注記バッジ",
    kind: "text",
    maxLen: 20,
    defaultText: "全国650台限定の伝説色",
  },
  {
    key: "home.colorlineup.swatch.5.code",
    page: "home",
    route: "/",
    label: "トップ / 色見本5 型式コード",
    kind: "text",
    maxLen: 30,
    defaultText: "TOYOTA 202 / SOLID",
  },
  {
    key: "home.colorlineup.swatch.5.name",
    page: "home",
    route: "/",
    label: "トップ / 色見本5 色名",
    kind: "text",
    maxLen: 20,
    defaultText: "ブラック",
  },
  {
    key: "home.colorlineup.swatch.5.note",
    page: "home",
    route: "/",
    label: "トップ / 色見本5 注記バッジ",
    kind: "text",
    maxLen: 20,
    defaultText: "最難関ソリッド黒",
  },
  {
    key: "home.colorlineup.swatch.6.code",
    page: "home",
    route: "/",
    label: "トップ / 色見本6 型式コード",
    kind: "text",
    maxLen: 30,
    defaultText: "NISSAN TV2 / 3COAT",
  },
  {
    key: "home.colorlineup.swatch.6.name",
    page: "home",
    route: "/",
    label: "トップ / 色見本6 色名",
    kind: "text",
    maxLen: 20,
    defaultText: "ベイサイドブルー",
  },
  {
    key: "home.colorlineup.swatch.6.note",
    page: "home",
    route: "/",
    label: "トップ / 色見本6 注記バッジ",
    kind: "text",
    maxLen: 20,
    defaultText: "R34 GT-Rの代名詞",
  },
  {
    key: "home.colorlineup.swatch.7.code",
    page: "home",
    route: "/",
    label: "トップ / 色見本7 型式コード",
    kind: "text",
    maxLen: 30,
    defaultText: "ASTON MARTIN AM9539",
  },
  {
    key: "home.colorlineup.swatch.7.name",
    page: "home",
    route: "/",
    label: "トップ / 色見本7 色名",
    kind: "text",
    maxLen: 20,
    defaultText: "レーシンググリーン",
  },
  {
    key: "home.colorlineup.swatch.7.note",
    page: "home",
    route: "/",
    label: "トップ / 色見本7 注記バッジ",
    kind: "text",
    maxLen: 20,
    defaultText: "英国の象徴色",
  },
  {
    key: "home.colorlineup.swatch.8.code",
    page: "home",
    route: "/",
    label: "トップ / 色見本8 型式コード",
    kind: "text",
    maxLen: 30,
    defaultText: "MAZDA 46G / METALLIC",
  },
  {
    key: "home.colorlineup.swatch.8.name",
    page: "home",
    route: "/",
    label: "トップ / 色見本8 色名",
    kind: "text",
    maxLen: 20,
    defaultText: "マシーングレー",
  },
  {
    key: "home.colorlineup.swatch.8.note",
    page: "home",
    route: "/",
    label: "トップ / 色見本8 注記バッジ",
    kind: "text",
    maxLen: 20,
    defaultText: "匠塗のもう一枚の看板",
  },
  {
    key: "home.colorlineup.cta",
    page: "home",
    route: "/",
    label: "トップ / COLOR LINEUP ボタン (COLORS導線)",
    kind: "text",
    maxLen: 20,
    defaultText: "色見本を一枚ずつ見る",
  },
  {
    key: "home.colorlineup.hint",
    page: "home",
    route: "/",
    label: "トップ / 色見本ストリップ操作ヒント",
    kind: "text",
    maxLen: 25,
    defaultText: "DRAG / SCROLL →",
  },

  // -- TWO SCENES --------------------------------------------------------
  {
    key: "home.twoscenes.label",
    page: "home",
    route: "/",
    label: "トップ / SEC.04 セクションラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "TWO SCENES",
  },
  {
    key: "home.twoscenes.scene.1.unit",
    page: "home",
    route: "/",
    label: "トップ / TWO SCENES シーン1 単位ラベル",
    kind: "text",
    maxLen: 25,
    defaultText: "PIECES / 勝負試作",
  },
  {
    key: "home.twoscenes.scene.2.unit",
    page: "home",
    route: "/",
    label: "トップ / TWO SCENES シーン2 単位ラベル",
    kind: "text",
    maxLen: 25,
    defaultText: "PIECES / ブリッジ生産",
  },
  {
    key: "home.twoscenes.scene.1.body",
    page: "home",
    route: "/",
    label: "トップ / TWO SCENES シーン1 本文",
    kind: "text",
    maxLen: 90,
    defaultText:
      "企業トップへの最終プレゼン、重要商談、展示会、クラウドファンディングの掲載写真。「絶対に外せない場面」で使う高品質試作を、量産品の顔に仕上げます。",
  },
  {
    key: "home.twoscenes.scene.2.body",
    page: "home",
    route: "/",
    label: "トップ / TWO SCENES シーン2 本文",
    kind: "text",
    maxLen: 85,
    defaultText:
      "クラウドファンディングのリターン品、D2Cの初回ロット、産業機器の筐体。金型なしの少量生産を「量産品の見た目」にする最終工程を担います。",
  },
  {
    key: "home.twoscenes.body",
    page: "home",
    route: "/",
    label: "トップ / TWO SCENES 補足本文",
    kind: "text",
    maxLen: 90,
    defaultText:
      "試作を仕上げたその手で、量産も仕上げる。クラウドファンディング達成の瞬間に「試作と同じ品質で数百個できます」と言える供給者は、ほとんどいません。",
  },

  // -- BY THE NUMBERS ------------------------------------------------------
  {
    key: "home.stats.label",
    page: "home",
    route: "/",
    label: "トップ / SEC.05 セクションラベル",
    kind: "text",
    maxLen: 25,
    defaultText: "BY THE NUMBERS",
  },
  {
    key: "home.stats.stat.1.unit",
    page: "home",
    route: "/",
    label: "トップ / STAT1 単位",
    kind: "text",
    maxLen: 10,
    defaultText: "本",
  },
  {
    key: "home.stats.stat.1.label",
    page: "home",
    route: "/",
    label: "トップ / STAT1 ラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "バンパー同時塗装",
  },
  {
    key: "home.stats.stat.1.en",
    page: "home",
    route: "/",
    label: "トップ / STAT1 英字ラベル",
    kind: "text",
    maxLen: 35,
    defaultText: "SIMULTANEOUS BUMPERS",
  },
  {
    key: "home.stats.stat.1.note",
    page: "home",
    route: "/",
    label: "トップ / STAT1 注記",
    kind: "text",
    maxLen: 65,
    defaultText:
      "この同時処理能力があるから、小物なら100個超を一度に。数量対応力は、そのまま価格に還元されます。",
  },
  {
    key: "home.stats.stat.2.label",
    page: "home",
    route: "/",
    label: "トップ / STAT2 ラベル",
    kind: "text",
    maxLen: 18,
    defaultText: "段階研磨の番手",
  },
  {
    key: "home.stats.stat.2.en",
    page: "home",
    route: "/",
    label: "トップ / STAT2 英字ラベル",
    kind: "text",
    maxLen: 28,
    defaultText: "PROGRESSIVE GRIT",
  },
  {
    key: "home.stats.stat.2.note",
    page: "home",
    route: "/",
    label: "トップ / STAT2 注記",
    kind: "text",
    maxLen: 65,
    defaultText:
      "粗い番手から徐々に上げる段階研磨。海外の現場で「射出成形品と見分けがつかない」とされる面の基準です。",
  },
  {
    key: "home.stats.stat.3.unit",
    page: "home",
    route: "/",
    label: "トップ / STAT3 単位",
    kind: "text",
    maxLen: 10,
    defaultText: "色",
  },
  {
    key: "home.stats.stat.3.label",
    page: "home",
    route: "/",
    label: "トップ / STAT3 ラベル",
    kind: "text",
    maxLen: 25,
    defaultText: "名車の象徴色ラインナップ",
  },
  {
    key: "home.stats.stat.3.en",
    page: "home",
    route: "/",
    label: "トップ / STAT3 英字ラベル",
    kind: "text",
    maxLen: 28,
    defaultText: "SIGNATURE COLORS",
  },
  {
    key: "home.stats.stat.3.note",
    page: "home",
    route: "/",
    label: "トップ / STAT3 注記",
    kind: "text",
    maxLen: 65,
    defaultText:
      "うち5色が3コート・高難度系。ソウルレッドもベイサイドブルーも、塗れること自体が技術の証明です。",
  },
  {
    key: "home.stats.stat.4.label",
    page: "home",
    route: "/",
    label: "トップ / STAT4 ラベル",
    kind: "text",
    maxLen: 18,
    defaultText: "対応数量（点）",
  },
  {
    key: "home.stats.stat.4.en",
    page: "home",
    route: "/",
    label: "トップ / STAT4 英字ラベル",
    kind: "text",
    maxLen: 28,
    defaultText: "PIECES PER ORDER",
  },
  {
    key: "home.stats.stat.4.note",
    page: "home",
    route: "/",
    label: "トップ / STAT4 注記",
    kind: "text",
    maxLen: 60,
    defaultText:
      "勝負試作の一点から、ブリッジ生産の千個まで。試作と量産を、同じ品質基準で仕上げます。",
  },
  {
    key: "home.stats.stat.5.unit",
    page: "home",
    route: "/",
    label: "トップ / STAT5 単位",
    kind: "text",
    maxLen: 10,
    defaultText: "時間",
  },
  {
    key: "home.stats.stat.5.label",
    page: "home",
    route: "/",
    label: "トップ / STAT5 ラベル",
    kind: "text",
    maxLen: 25,
    defaultText: "最高級の黒が下地にかける時間",
  },
  {
    key: "home.stats.stat.5.en",
    page: "home",
    route: "/",
    label: "トップ / STAT5 英字ラベル",
    kind: "text",
    maxLen: 35,
    defaultText: 'CENTURY "KAMUI" BLACK',
  },
  {
    key: "home.stats.stat.5.note",
    page: "home",
    route: "/",
    label: "トップ / STAT5 注記",
    kind: "text",
    maxLen: 70,
    defaultText:
      "名車センチュリーの黒は、塗装だけで約40時間・水研ぎ3回。その下地への敬意を、すべての仕事に持ち込みます。",
  },
  {
    key: "home.stats.stat.6.unit",
    page: "home",
    route: "/",
    label: "トップ / STAT6 単位",
    kind: "text",
    maxLen: 10,
    defaultText: "日",
  },
  {
    key: "home.stats.stat.6.label",
    page: "home",
    route: "/",
    label: "トップ / STAT6 ラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "2液ウレタン完全硬化",
  },
  {
    key: "home.stats.stat.6.en",
    page: "home",
    route: "/",
    label: "トップ / STAT6 英字ラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "FULL CURE",
  },
  {
    key: "home.stats.stat.6.note",
    page: "home",
    route: "/",
    label: "トップ / STAT6 注記",
    kind: "text",
    maxLen: 60,
    defaultText:
      "主剤と硬化剤の化学反応で硬く艶やかに。硬化を待ち、検品してから発送します。急がば、回る。",
  },

  // -- MATERIALS 導線 ----------------------------------------------------
  {
    key: "home.materials.label",
    page: "home",
    route: "/",
    label: "トップ / SEC.06 セクションラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "MATERIALS",
  },
  {
    key: "home.materials.body",
    page: "home",
    route: "/",
    label: "トップ / MATERIALS 導線本文",
    kind: "text",
    maxLen: 140,
    defaultText:
      "造形方式が違えば、積層痕の出方も塗料の乗り方も変わります。FDMは研磨で埋め、光造形は洗浄と二次硬化を前提にし、SLSは多孔質を作り込む。PLA・PETG・ABS・ASA、各種レジン、ナイロンまで、素材別の勘所をまとめています。",
  },
  {
    key: "home.materials.cta",
    page: "home",
    route: "/",
    label: "トップ / MATERIALS ボタン (MATERIALS導線)",
    kind: "text",
    maxLen: 20,
    defaultText: "素材別の対応を見る",
  },

  // -- NOTES 導線 ----------------------------------------------------------
  {
    key: "home.notes.label",
    page: "home",
    route: "/",
    label: "トップ / SEC.07 セクションラベル",
    kind: "text",
    maxLen: 16,
    defaultText: "NOTES",
  },
  {
    key: "home.notes.body",
    page: "home",
    route: "/",
    label: "トップ / NOTES 導線本文",
    kind: "text",
    maxLen: 100,
    defaultText:
      "工程と色の裏側を、読みものとして残しています。センチュリーの黒が水研ぎ3回である理由。ディーラーでも同色にならない赤の構造。専門性は、言葉にしてはじめて伝わります。",
  },
  {
    key: "home.notes.cta",
    page: "home",
    route: "/",
    label: "トップ / NOTES ボタン (NOTES導線)",
    kind: "text",
    maxLen: 16,
    defaultText: "読みものを開く",
  },

  // -- GALLERY -----------------------------------------------------------
  {
    key: "home.gallery.label",
    page: "home",
    route: "/",
    label: "トップ / GALLERY セクションラベル",
    kind: "text",
    maxLen: 25,
    defaultText: "IN THE WORKSHOP",
  },
  {
    key: "home.gallery.body",
    page: "home",
    route: "/",
    label: "トップ / GALLERY 補足本文",
    kind: "text",
    maxLen: 35,
    defaultText: "研ぎ、吹き、仕上げる。派手さのない手仕事の断片を。",
  },
  {
    key: "home.gallery.1.capja",
    page: "home",
    route: "/",
    label: "トップ / FIG.04 (GALLERY写真1) 日本語キャプション",
    kind: "text",
    maxLen: 16,
    defaultText: "手を動かす",
  },
  {
    key: "home.gallery.1.capen",
    page: "home",
    route: "/",
    label: "トップ / FIG.04 (GALLERY写真1) 英語キャプション",
    kind: "text",
    maxLen: 25,
    defaultText: "HANDS AT WORK",
  },
  {
    key: "home.gallery.1.credit",
    page: "home",
    route: "/",
    label: "トップ / FIG.04 (GALLERY写真1) クレジット表記",
    kind: "text",
    maxLen: 40,
    defaultText: "Photo: claritycoat / Unsplash",
  },
  {
    key: "home.gallery.2.capja",
    page: "home",
    route: "/",
    label: "トップ / FIG.05 (GALLERY写真2) 日本語キャプション",
    kind: "text",
    maxLen: 16,
    defaultText: "段取り",
  },
  {
    key: "home.gallery.2.capen",
    page: "home",
    route: "/",
    label: "トップ / FIG.05 (GALLERY写真2) 英語キャプション",
    kind: "text",
    maxLen: 20,
    defaultText: "THE TOOLING",
  },
  {
    key: "home.gallery.2.credit",
    page: "home",
    route: "/",
    label: "トップ / FIG.05 (GALLERY写真2) クレジット表記",
    kind: "text",
    maxLen: 35,
    defaultText: "Photo: volft / Unsplash",
  },
  {
    key: "home.gallery.3.capja",
    page: "home",
    route: "/",
    label: "トップ / FIG.06 (GALLERY写真3) 日本語キャプション",
    kind: "text",
    maxLen: 16,
    defaultText: "精度",
  },
  {
    key: "home.gallery.3.capen",
    page: "home",
    route: "/",
    label: "トップ / FIG.06 (GALLERY写真3) 英語キャプション",
    kind: "text",
    maxLen: 25,
    defaultText: "THE MACHINERY",
  },
  {
    key: "home.gallery.3.credit",
    page: "home",
    route: "/",
    label: "トップ / FIG.06 (GALLERY写真3) クレジット表記",
    kind: "text",
    maxLen: 40,
    defaultText: "Photo: kadircelep / Unsplash",
  },
];
