import type { PageTextSlot } from "../types";

// ---------------------------------------------------------------------------
// home (15, route: "/")
// ---------------------------------------------------------------------------
export const HOME_TEXT_SLOTS: readonly PageTextSlot[] = [
  {
    key: "home.statement.heading",
    page: "home",
    route: "/",
    label: "トップ / STATEMENT 見出し",
    kind: "lines",
    maxLen: 90,
    defaultText:
      "デザインモデルの品質は、\n表面処理で決まる。\nそれでも、表面処理を高い水準で\n内製できる会社は、多くない。\nその空白のために、この工房がある。",
    maxLines: 5,
    maxLineLen: 18,
  },
  {
    key: "home.craft.heading",
    page: "home",
    route: "/",
    label: "トップ / CRAFT 見出し",
    kind: "text",
    maxLen: 24,
    defaultText: "3つの技術を、ひとりで持つ。",
  },
  {
    key: "home.craft.card.1.title",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード1 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "積層痕を消す研磨",
  },
  {
    key: "home.craft.card.2.title",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード2 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "自動車グレードの艶",
  },
  {
    key: "home.craft.card.3.title",
    page: "home",
    route: "/",
    label: "トップ / CRAFTカード3 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "3コートパールの意匠",
  },
  {
    key: "home.colorlineup.heading",
    page: "home",
    route: "/",
    label: "トップ / COLOR LINEUP 見出し",
    kind: "lines",
    maxLen: 30,
    defaultText: "名車の象徴色で組んだ、\n8枚の技術証明。",
    maxLines: 2,
  },
  {
    key: "home.twoscenes.heading",
    page: "home",
    route: "/",
    label: "トップ / TWO SCENES 見出し",
    kind: "text",
    maxLen: 26,
    defaultText: "一点の勝負にも、千個の生産にも。",
  },
  {
    key: "home.twoscenes.scene.1.title",
    page: "home",
    route: "/",
    label: "トップ / TWO SCENES シーン1 見出し",
    kind: "text",
    maxLen: 28,
    defaultText: "プレミアムデザインモデルの一点仕上げ",
  },
  {
    key: "home.twoscenes.scene.2.title",
    page: "home",
    route: "/",
    label: "トップ / TWO SCENES シーン2 見出し",
    kind: "text",
    maxLen: 28,
    defaultText: "金型を作らない少量生産の外観仕上げ",
  },
  {
    key: "home.stats.heading",
    page: "home",
    route: "/",
    label: "トップ / BY THE NUMBERS 見出し",
    kind: "lines",
    maxLen: 20,
    defaultText: "工房の能力を、\n数字で。",
    maxLines: 2,
  },
  {
    key: "home.materials.heading",
    page: "home",
    route: "/",
    label: "トップ / MATERIALS 導線見出し",
    kind: "lines",
    maxLen: 40,
    defaultText: "FDMも、光造形も、SLSも。\n素材ごとに、手を変える。",
    maxLines: 2,
  },
  {
    key: "home.notes.heading",
    page: "home",
    route: "/",
    label: "トップ / NOTES 導線見出し",
    kind: "lines",
    maxLen: 32,
    defaultText: "なぜ綺麗なのかは、\n写真だけでは伝わらない。",
    maxLines: 2,
  },
  {
    key: "home.gallery.heading",
    page: "home",
    route: "/",
    label: "トップ / GALLERY 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "工房の、手の記録。",
  },
  {
    key: "home.cta.heading",
    page: "home",
    route: "/",
    label: "トップ / CTA帯 見出し",
    kind: "lines",
    maxLen: 44,
    defaultText: "見積もりは、3つの数字で。\nサイズ × 個数 × グレード。",
    maxLines: 2,
  },
  {
    key: "home.cta.note",
    page: "home",
    route: "/",
    label: "トップ / CTA帯 補足",
    kind: "text",
    maxLen: 60,
    defaultText: "造形データや写真があれば、より正確に概算をお出しできます。",
  },
];
