import type { PageTextSlot } from "../types";

// ---------------------------------------------------------------------------
// materials (9, route: "/materials")
// ---------------------------------------------------------------------------
export const MATERIALS_TEXT_SLOTS: readonly PageTextSlot[] = [
  {
    key: "materials.hero.heading",
    page: "materials",
    route: "/materials",
    label: "素材対応 / ヒーロー見出し",
    kind: "lines",
    maxLen: 36,
    defaultText: "素材を選ばない。\nただし、素材ごとに手を変える。",
    maxLines: 2,
    maxLineLen: 20,
  },
  {
    key: "materials.hero.lead",
    page: "materials",
    route: "/materials",
    label: "素材対応 / ヒーローリード文",
    kind: "multiline",
    maxLen: 200,
    defaultText:
      "3Dプリントは、造形方式によって積層痕の出方も、塗料の乗り方も、まったく違います。FDMは研磨で埋め、光造形は洗浄と二次硬化を前提にし、SLSは多孔質を作り込む——同じ「下地」でも、素材ごとに手を変えます。ここでは対応方式と、素材別の考え方をまとめます。",
  },
  {
    key: "materials.methods.heading",
    page: "materials",
    route: "/materials",
    label: "素材対応 / PRINTING METHODS 見出し",
    kind: "lines",
    maxLen: 24,
    defaultText: "3つの造形方式、\nそれぞれの下地。",
    maxLines: 2,
  },
  {
    key: "materials.matrix.heading",
    page: "materials",
    route: "/materials",
    label: "素材対応 / MATERIAL MATRIX 見出し",
    kind: "text",
    maxLen: 18,
    defaultText: "素材別の、対応と勘所。",
  },
  {
    key: "materials.why.heading",
    page: "materials",
    route: "/materials",
    label: "素材対応 / WHY IT MATTERS 見出し",
    kind: "lines",
    maxLen: 26,
    defaultText: "失敗の多くは、\n塗る前に決まっている。",
    maxLines: 2,
  },
  {
    key: "materials.intake.heading",
    page: "materials",
    route: "/materials",
    label: "素材対応 / DATA INTAKE 見出し",
    kind: "text",
    maxLen: 20,
    defaultText: "造形から、任せてもいい。",
  },
  {
    key: "materials.gallery.heading",
    page: "materials",
    route: "/materials",
    label: "素材対応 / GALLERY 見出し",
    kind: "text",
    maxLen: 14,
    defaultText: "素材の、その先。",
  },
  {
    key: "materials.cta.heading",
    page: "materials",
    route: "/materials",
    label: "素材対応 / CTA帯 見出し",
    kind: "lines",
    maxLen: 44,
    defaultText: "素材が決まっていなくても、\n用途から相談できます。",
    maxLines: 2,
  },
  {
    key: "materials.cta.note",
    page: "materials",
    route: "/materials",
    label: "素材対応 / CTA帯 補足",
    kind: "text",
    maxLen: 60,
    defaultText: "「屋外で使う」「撮影用」「触れる展示物」——用途に合う素材と仕上げをご提案します。",
  },
];
