import type { PageTextSlot } from "../types";

// ---------------------------------------------------------------------------
// notes (13, route: "/notes") — notes.cta.* / notes.hero.index / notes.hero.en は
// notes/[slug] とも共有 (PLAN.md §5.8)。v2 Wave 1: 既存4件はそのまま維持し、
// page-body.tsx (一覧) / [slug]/page-body.tsx (詳細) の残り全静的テキストを追加。
// SectionMark の no ("SEC. 01") は home.ts と同じ precedent により対象外。
// post.title / post.excerpt / post.body / formatNoteNo の連番表示は DB 由来のため対象外。
// ---------------------------------------------------------------------------
export const NOTES_TEXT_SLOTS: readonly PageTextSlot[] = [
  {
    key: "notes.hero.heading",
    page: "notes",
    route: "/notes",
    label: "読みもの / ヒーロー見出し",
    kind: "lines",
    maxLen: 34,
    defaultText: "なぜ綺麗なのかは、\n写真だけでは伝わらない。",
    maxLines: 2,
    maxLineLen: 20,
  },
  {
    key: "notes.hero.lead",
    page: "notes",
    route: "/notes",
    label: "読みもの / ヒーローリード文",
    kind: "multiline",
    maxLen: 200,
    defaultText: "工程と色の裏側を、言葉で残しています。専門性は、言語化してはじめて伝わる——それがこの工房の考え方です。",
  },
  {
    key: "notes.cta.heading",
    page: "notes",
    route: "/notes",
    label: "読みもの / CTA帯 見出し (一覧・詳細で共有)",
    kind: "lines",
    maxLen: 44,
    defaultText: "読んで気になったことは、\nそのまま聞いてください。",
    maxLines: 2,
    affectedRoutes: ["/notes", "notes/[slug]"],
  },
  {
    key: "notes.cta.note",
    page: "notes",
    route: "/notes",
    label: "読みもの / CTA帯 補足 (一覧・詳細で共有)",
    kind: "text",
    maxLen: 60,
    defaultText: "工程・色・素材の相性、どんな質問でも。",
    affectedRoutes: ["/notes", "notes/[slug]"],
  },
  {
    key: "notes.hero.index",
    page: "notes",
    route: "/notes",
    label: "読みもの / ヒーロー連番表記 (一覧・詳細で共有)",
    kind: "text",
    maxLen: 25,
    defaultText: "INDEX 08 — NOTES",
    affectedRoutes: ["/notes", "notes/[slug]"],
  },
  {
    key: "notes.hero.en",
    page: "notes",
    route: "/notes",
    label: "読みもの / ヒーロー英字サブラベル (一覧・詳細で共有)",
    kind: "text",
    maxLen: 35,
    defaultText: "READING ON PAINT & COLOR",
    affectedRoutes: ["/notes", "notes/[slug]"],
  },
  {
    key: "notes.articles.label",
    page: "notes",
    route: "/notes",
    label: "読みもの / SEC.01 セクションラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "ARTICLES",
  },
  {
    key: "notes.empty.message",
    page: "notes",
    route: "/notes",
    label: "読みもの / 記事0件時の空状態メッセージ",
    kind: "text",
    maxLen: 55,
    defaultText: "読みものは現在準備中です。工程・色の裏側を、順次言葉にして公開していきます。",
  },
  {
    key: "notes.comingsoon.label",
    page: "notes",
    route: "/notes",
    label: "読みもの / COMING SOON ラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "COMING SOON",
  },
  {
    key: "notes.comingsoon.body",
    page: "notes",
    route: "/notes",
    label: "読みもの / COMING SOON 本文 (改行区切り)",
    kind: "lines",
    maxLen: 90,
    defaultText:
      "今後、デモピースの製作記録や案件の実績（掲載許諾をいただいたもの）を、ここで発信していきます。\nnote・X・Instagram との連携も準備中です。",
    maxLines: 2,
    maxLineLen: 60,
  },
  {
    key: "notes.detail.prev.label",
    page: "notes",
    route: "notes/[slug]",
    label: "読みもの詳細 / 前の記事ナビラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "← PREV — 前の記事",
  },
  {
    key: "notes.detail.next.label",
    page: "notes",
    route: "notes/[slug]",
    label: "読みもの詳細 / 次の記事ナビラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "NEXT — 次の記事 →",
  },
  {
    key: "notes.detail.back",
    page: "notes",
    route: "notes/[slug]",
    label: "読みもの詳細 / 一覧に戻るボタン",
    kind: "text",
    maxLen: 20,
    defaultText: "読みもの一覧に戻る",
  },
];
