import type { PageTextSlot } from "../types";

// ---------------------------------------------------------------------------
// process (9, route: "/process")
// ---------------------------------------------------------------------------
export const PROCESS_TEXT_SLOTS: readonly PageTextSlot[] = [
  {
    key: "process.hero.heading",
    page: "process",
    route: "/process",
    label: "工程 / ヒーロー見出し",
    kind: "lines",
    maxLen: 28,
    defaultText: "一個が仕上がるまでの、\n9つの手。",
    maxLines: 2,
    maxLineLen: 20,
  },
  {
    key: "process.hero.lead",
    page: "process",
    route: "/process",
    label: "工程 / ヒーローリード文",
    kind: "multiline",
    maxLen: 200,
    defaultText:
      "3Dプリントの造形物が、量産品と見分けがつかない外観になるまでには、決まった順序があります。派手なのは色を吹く瞬間だけ。その前後にある地味な工程こそが、仕上がりを決めます。自動車補修の手順を、一手ずつ開きます。",
  },
  {
    key: "process.coating.heading",
    page: "process",
    route: "/process",
    label: "工程 / COATING STRUCTURE 見出し",
    kind: "lines",
    maxLen: 24,
    defaultText: "塗装は、\n層でできている。",
    maxLines: 2,
  },
  {
    key: "process.steps.heading",
    page: "process",
    route: "/process",
    label: "工程 / THE 9 STEPS 見出し",
    kind: "lines",
    maxLen: 24,
    defaultText: "受け取ってから、\n送り出すまで。",
    maxLines: 2,
  },
  {
    key: "process.booth.heading",
    page: "process",
    route: "/process",
    label: "工程 / THE BOOTH 見出し",
    kind: "lines",
    maxLen: 28,
    defaultText: "きれいな空気でしか、\nきれいには塗れない。",
    maxLines: 2,
  },
  {
    key: "process.related.heading",
    page: "process",
    route: "/process",
    label: "工程 / RELATED 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "工程の、その先へ。",
  },
  {
    key: "process.gallery.heading",
    page: "process",
    route: "/process",
    label: "工程 / GALLERY 見出し",
    kind: "text",
    maxLen: 18,
    defaultText: "工程を、支えるもの。",
  },
  {
    key: "process.cta.heading",
    page: "process",
    route: "/process",
    label: "工程 / CTA帯 見出し",
    kind: "lines",
    maxLen: 44,
    defaultText: "この9工程を、\nあなたの一個に。",
    maxLines: 2,
  },
  {
    key: "process.cta.note",
    page: "process",
    route: "/process",
    label: "工程 / CTA帯 補足",
    kind: "text",
    maxLen: 60,
    defaultText: "サイズ・個数・グレードが分かれば、概算をお出しできます。まずはご相談ください。",
  },
];
