import type { PageTextSlot } from "../types";

// ---------------------------------------------------------------------------
// process (9, route: "/process")
// ---------------------------------------------------------------------------
export const PROCESS_TEXT_SLOTS: readonly PageTextSlot[] = [
  {
    key: "process.hero.heading",
    page: "process",
    route: "/process",
    label: "工程 / ヒーロー見出し",
    kind: "lines",
    maxLen: 28,
    defaultText: "一個が仕上がるまでの、\n9つの手。",
    maxLines: 2,
    maxLineLen: 20,
  },
  {
    key: "process.hero.lead",
    page: "process",
    route: "/process",
    label: "工程 / ヒーローリード文",
    kind: "multiline",
    maxLen: 200,
    defaultText:
      "3Dプリントの造形物が、量産品と見分けがつかない外観になるまでには、決まった順序があります。派手なのは色を吹く瞬間だけ。その前後にある地味な工程こそが、仕上がりを決めます。自動車補修の手順を、一手ずつ開きます。",
  },
  {
    key: "process.coating.heading",
    page: "process",
    route: "/process",
    label: "工程 / COATING STRUCTURE 見出し",
    kind: "lines",
    maxLen: 24,
    defaultText: "塗装は、\n層でできている。",
    maxLines: 2,
  },
  {
    key: "process.steps.heading",
    page: "process",
    route: "/process",
    label: "工程 / THE 9 STEPS 見出し",
    kind: "lines",
    maxLen: 24,
    defaultText: "受け取ってから、\n送り出すまで。",
    maxLines: 2,
  },
  {
    key: "process.booth.heading",
    page: "process",
    route: "/process",
    label: "工程 / THE BOOTH 見出し",
    kind: "lines",
    maxLen: 28,
    defaultText: "きれいな空気でしか、\nきれいには塗れない。",
    maxLines: 2,
  },
  {
    key: "process.related.heading",
    page: "process",
    route: "/process",
    label: "工程 / RELATED 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "工程の、その先へ。",
  },
  {
    key: "process.gallery.heading",
    page: "process",
    route: "/process",
    label: "工程 / GALLERY 見出し",
    kind: "text",
    maxLen: 18,
    defaultText: "工程を、支えるもの。",
  },
  {
    key: "process.cta.heading",
    page: "process",
    route: "/process",
    label: "工程 / CTA帯 見出し",
    kind: "lines",
    maxLen: 44,
    defaultText: "この9工程を、\nあなたの一個に。",
    maxLines: 2,
  },
  {
    key: "process.cta.note",
    page: "process",
    route: "/process",
    label: "工程 / CTA帯 補足",
    kind: "text",
    maxLen: 60,
    defaultText: "サイズ・個数・グレードが分かれば、概算をお出しできます。まずはご相談ください。",
  },

  // ---------------------------------------------------------------------------
  // v2 Wave 1 追加分 (docs/design/visual-text-editor-v2.md §5): 上記9件は既存のまま維持し、
  // page-body.tsx の残り全静的テキストを追加。defaultText は現行描画テキストと1文字も違わない
  // (非退行)。rich kind の語彙は mono(`text`) / strong(**text**) の2種のみ使用 (§3.1)。
  //
  // 配線方針の決定事項:
  // - PhotoFigure の figNo ("FIG.02a" 等) と STEPS の連番 ("01".."09")、SectionMark の
  //   no ("SEC. 01" 等) は他ページ (shop 等) と同じ理由で対象外 (構造的な連番表記、
  //   非slot化が確立された規約)。SectionMark の label のみ labelSlotKey で配線する。
  // - STEP 固定ラベル ("STEP") は9箇所とも同一文言だが、各工程が個別に持つ (plain ×9)。
  // - rich(strong) = process.step.N.why (全9件、固定ラベル **なぜ** + 理由文。
  //   02,03,05,07,08,09 は理由文中にさらに1箇所 **強調** を含む。現行 JSX の strong 範囲を
  //   厳密に再現)。
  // - rich(mono) = process.step.2.desc / process.step.6.desc (研磨番手 `#800` / `#1200` を
  //   文中インラインで含む)。他7工程の desc は装飾なし (plain)。
  // - process.step.N.en は全体が font-mono な別フィールド (PhotoFigure capEn と同じ理由で
  //   plain。SANDING — #800 等の # 表記もインライン装飾ではなく地の文字列としてそのまま)。
  // - THE BOOTH の fact.3.unit は現行が空文字 ("") のため slot化しない (span は空のまま
  //   構造だけ保持)。
  // ---------------------------------------------------------------------------

  // --- PageHead ---
  {
    key: "process.hero.index",
    page: "process",
    route: "/process",
    label: "工程 / PageHead 連番表記 (INDEX NN — ページ名)",
    kind: "text",
    maxLen: 35,
    defaultText: "PROCESS — 塗りが仕上がるまで",
  },
  {
    key: "process.hero.en",
    page: "process",
    route: "/process",
    label: "工程 / PageHead 英字サブラベル",
    kind: "text",
    maxLen: 15,
    defaultText: "9 STEPS",
  },

  // --- SEC.01 COATING STRUCTURE ---
  {
    key: "process.sec.1.label",
    page: "process",
    route: "/process",
    label: "工程 / SEC.01 セクションラベル",
    kind: "text",
    maxLen: 30,
    defaultText: "COATING STRUCTURE",
  },
  {
    key: "process.coating.lead",
    page: "process",
    route: "/process",
    label: "工程 / COATING STRUCTURE リード文",
    kind: "text",
    maxLen: 125,
    defaultText:
      "仕上がった塗面は一枚に見えますが、実際は役割の違う層の積み重ねです。下から順に、造形物・プラサフ・ベースコート・クリア。積層痕は、下の層で吸収して消します。",
  },
  {
    key: "process.legend.1.name",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例1 名称",
    kind: "text",
    maxLen: 10,
    defaultText: "造形物",
  },
  {
    key: "process.legend.1.en",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例1 英字ラベル",
    kind: "text",
    maxLen: 15,
    defaultText: "3D PRINT",
  },
  {
    key: "process.legend.1.desc",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例1 説明文",
    kind: "text",
    maxLen: 35,
    defaultText: "出発点。表面には積層痕という横縞がある。",
  },
  {
    key: "process.legend.2.name",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例2 名称",
    kind: "text",
    maxLen: 10,
    defaultText: "プラサフ",
  },
  {
    key: "process.legend.2.en",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例2 英字ラベル",
    kind: "text",
    maxLen: 25,
    defaultText: "PRIMER-SURFACER",
  },
  {
    key: "process.legend.2.desc",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例2 説明文",
    kind: "text",
    maxLen: 40,
    defaultText: "積層痕を埋めて平滑化し、塗料の密着をつくる下地。",
  },
  {
    key: "process.legend.3.name",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例3 名称",
    kind: "text",
    maxLen: 10,
    defaultText: "ベースコート",
  },
  {
    key: "process.legend.3.en",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例3 英字ラベル",
    kind: "text",
    maxLen: 15,
    defaultText: "BASE COAT",
  },
  {
    key: "process.legend.3.desc",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例3 説明文",
    kind: "text",
    maxLen: 40,
    defaultText: "色を決める発色層。メタリック・パールもこの層。",
  },
  {
    key: "process.legend.4.name",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例4 名称",
    kind: "text",
    maxLen: 10,
    defaultText: "クリア",
  },
  {
    key: "process.legend.4.en",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例4 英字ラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "CLEAR (2K)",
  },
  {
    key: "process.legend.4.desc",
    page: "process",
    route: "/process",
    label: "工程 / 塗膜凡例4 説明文",
    kind: "text",
    maxLen: 40,
    defaultText: "2液ウレタン。色を守り、磨かずとも深い艶を出す。",
  },

  // --- SEC.02 THE 9 STEPS ---
  {
    key: "process.sec.2.label",
    page: "process",
    route: "/process",
    label: "工程 / SEC.02 セクションラベル",
    kind: "text",
    maxLen: 20,
    defaultText: "THE 9 STEPS",
  },
  {
    key: "process.steps.1.capja",
    page: "process",
    route: "/process",
    label: "工程 / FIG.02a 日本語キャプション",
    kind: "text",
    maxLen: 10,
    defaultText: "下地をつくる",
  },
  {
    key: "process.steps.1.capen",
    page: "process",
    route: "/process",
    label: "工程 / FIG.02a 英語キャプション",
    kind: "text",
    maxLen: 30,
    defaultText: "SANDING & PRIMER",
  },
  {
    key: "process.steps.1.credit",
    page: "process",
    route: "/process",
    label: "工程 / FIG.02a クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: mazinomron / Unsplash",
  },
  {
    key: "process.steps.2.capja",
    page: "process",
    route: "/process",
    label: "工程 / FIG.02b 日本語キャプション",
    kind: "text",
    maxLen: 10,
    defaultText: "色を吹く",
  },
  {
    key: "process.steps.2.capen",
    page: "process",
    route: "/process",
    label: "工程 / FIG.02b 英語キャプション",
    kind: "text",
    maxLen: 20,
    defaultText: "BASE & CLEAR",
  },
  {
    key: "process.steps.2.credit",
    page: "process",
    route: "/process",
    label: "工程 / FIG.02b クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: createasea / Unsplash",
  },
  {
    key: "process.steps.3.capja",
    page: "process",
    route: "/process",
    label: "工程 / FIG.02c 日本語キャプション",
    kind: "text",
    maxLen: 10,
    defaultText: "仕上がり",
  },
  {
    key: "process.steps.3.capen",
    page: "process",
    route: "/process",
    label: "工程 / FIG.02c 英語キャプション",
    kind: "text",
    maxLen: 20,
    defaultText: "THE FINISH",
  },
  {
    key: "process.steps.3.credit",
    page: "process",
    route: "/process",
    label: "工程 / FIG.02c クレジット表記",
    kind: "text",
    maxLen: 50,
    defaultText: "Photo: cmreflections / Unsplash",
  },
  {
    key: "process.step.1.label",
    page: "process",
    route: "/process",
    label: "工程 / STEP01 固定ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "STEP",
  },
  {
    key: "process.step.1.title",
    page: "process",
    route: "/process",
    label: "工程 / STEP01 タイトル",
    kind: "text",
    maxLen: 15,
    defaultText: "受け入れ・確認",
  },
  {
    key: "process.step.1.en",
    page: "process",
    route: "/process",
    label: "工程 / STEP01 英字ラベル",
    kind: "text",
    maxLen: 35,
    defaultText: "INTAKE & INSPECTION",
  },
  {
    key: "process.step.1.desc",
    page: "process",
    route: "/process",
    label: "工程 / STEP01 説明文",
    kind: "text",
    maxLen: 140,
    defaultText:
      "届いた造形物を確認します。造形方式と素材、積層痕の状態、欠けや反りの有無を見ます。初めての素材なら、いきなり本番にはせず、テストピースで塗料の相性を確かめてから進めます。",
  },
  {
    key: "process.step.1.why",
    page: "process",
    route: "/process",
    label: "工程 / STEP01 「なぜ」 (rich, strong)",
    kind: "rich",
    maxLen: 75,
    defaultText: "**なぜ** — 素材ごとに塗料の乗り方が違うから。最初の見極めが、後の失敗を防ぎます。",
  },
  {
    key: "process.step.2.label",
    page: "process",
    route: "/process",
    label: "工程 / STEP02 固定ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "STEP",
  },
  {
    key: "process.step.2.title",
    page: "process",
    route: "/process",
    label: "工程 / STEP02 タイトル",
    kind: "text",
    maxLen: 10,
    defaultText: "積層痕の研磨",
  },
  {
    key: "process.step.2.en",
    page: "process",
    route: "/process",
    label: "工程 / STEP02 英字ラベル",
    kind: "text",
    maxLen: 25,
    defaultText: "SANDING — #800",
  },
  {
    key: "process.step.2.desc",
    page: "process",
    route: "/process",
    label: "工程 / STEP02 説明文 (rich, 番手 #800 を文中インライン mono)",
    kind: "rich",
    maxLen: 125,
    defaultText:
      "`#800` の紙やすりで、積層痕を面ごと研ぎ落とします。ここで縞の大半を物理的に消します。細いディテールや薄い壁は、力を入れすぎないよう手加減しながら。",
  },
  {
    key: "process.step.2.why",
    page: "process",
    route: "/process",
    label: "工程 / STEP02 「なぜ」 (rich, strong ×2)",
    kind: "rich",
    maxLen: 75,
    defaultText:
      "**なぜ** — 積層痕は塗料では消えません。**縞を消すのは、塗料ではなく研ぎ**です。",
  },
  {
    key: "process.step.3.label",
    page: "process",
    route: "/process",
    label: "工程 / STEP03 固定ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "STEP",
  },
  {
    key: "process.step.3.title",
    page: "process",
    route: "/process",
    label: "工程 / STEP03 タイトル",
    kind: "text",
    maxLen: 10,
    defaultText: "洗浄・脱脂",
  },
  {
    key: "process.step.3.en",
    page: "process",
    route: "/process",
    label: "工程 / STEP03 英字ラベル",
    kind: "text",
    maxLen: 35,
    defaultText: "CLEANING & DEGREASING",
  },
  {
    key: "process.step.3.desc",
    page: "process",
    route: "/process",
    label: "工程 / STEP03 説明文",
    kind: "text",
    maxLen: 135,
    defaultText:
      "研磨後、水洗いで削りカスを流し、脱脂剤（シリコンオフ）で油分を除去、タッククロスで微粉を拭き取ります。光造形品は、未硬化レジンの洗浄と二次硬化もここまでに済ませます。",
  },
  {
    key: "process.step.3.why",
    page: "process",
    route: "/process",
    label: "工程 / STEP03 「なぜ」 (rich, strong ×2)",
    kind: "rich",
    maxLen: 95,
    defaultText:
      "**なぜ** — 油分が残ると塗料が弾き（ハジキ）、密着不良や膨れの原因に。**脱脂を怠ると、あとで必ず出ます。**",
  },
  {
    key: "process.step.4.label",
    page: "process",
    route: "/process",
    label: "工程 / STEP04 固定ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "STEP",
  },
  {
    key: "process.step.4.title",
    page: "process",
    route: "/process",
    label: "工程 / STEP04 タイトル",
    kind: "text",
    maxLen: 10,
    defaultText: "マスキング",
  },
  {
    key: "process.step.4.en",
    page: "process",
    route: "/process",
    label: "工程 / STEP04 英字ラベル",
    kind: "text",
    maxLen: 15,
    defaultText: "MASKING",
  },
  {
    key: "process.step.4.desc",
    page: "process",
    route: "/process",
    label: "工程 / STEP04 説明文",
    kind: "text",
    maxLen: 135,
    defaultText:
      "塗料を乗せない部分、塗り分ける境界を養生します。曲面や細部に沿ってテープを貼る精度が、塗り際の美しさを決めます。可動部や勘合部があれば、噛み合わせを保つよう保護します。",
  },
  {
    key: "process.step.4.why",
    page: "process",
    route: "/process",
    label: "工程 / STEP04 「なぜ」 (rich, strong)",
    kind: "rich",
    maxLen: 80,
    defaultText:
      "**なぜ** — マスキングの技術は、そのまま仕上がりの輪郭に出ます。地味ですが、差が出る工程です。",
  },
  {
    key: "process.step.5.label",
    page: "process",
    route: "/process",
    label: "工程 / STEP05 固定ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "STEP",
  },
  {
    key: "process.step.5.title",
    page: "process",
    route: "/process",
    label: "工程 / STEP05 タイトル",
    kind: "text",
    maxLen: 25,
    defaultText: "プラサフ（下塗り・中塗り）",
  },
  {
    key: "process.step.5.en",
    page: "process",
    route: "/process",
    label: "工程 / STEP05 英字ラベル",
    kind: "text",
    maxLen: 25,
    defaultText: "PRIMER-SURFACER",
  },
  {
    key: "process.step.5.desc",
    page: "process",
    route: "/process",
    label: "工程 / STEP05 説明文",
    kind: "text",
    maxLen: 135,
    defaultText:
      "プライマー（密着）とサーフェイサー（凹凸埋め）を兼ねたプラサフを吹きます。厚膜タイプで微細な段差を埋め、研磨で残った細かな傷を覆う。塗料が乗る土台を、ここでつくります。",
  },
  {
    key: "process.step.5.why",
    page: "process",
    route: "/process",
    label: "工程 / STEP05 「なぜ」 (rich, strong ×2)",
    kind: "rich",
    maxLen: 90,
    defaultText:
      "**なぜ** — サーフェイサーを省くと密着も発色も落ちます。**塗装の出来の大半は、この下地で決まる。**",
  },
  {
    key: "process.step.6.label",
    page: "process",
    route: "/process",
    label: "工程 / STEP06 固定ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "STEP",
  },
  {
    key: "process.step.6.title",
    page: "process",
    route: "/process",
    label: "工程 / STEP06 タイトル",
    kind: "text",
    maxLen: 15,
    defaultText: "足付け・水研ぎ",
  },
  {
    key: "process.step.6.en",
    page: "process",
    route: "/process",
    label: "工程 / STEP06 英字ラベル",
    kind: "text",
    maxLen: 35,
    defaultText: "WET-SANDING — #1200",
  },
  {
    key: "process.step.6.desc",
    page: "process",
    route: "/process",
    label: "工程 / STEP06 説明文 (rich, 番手 #1200 を文中インライン mono)",
    kind: "rich",
    maxLen: 130,
    defaultText:
      "プラサフが乾いたら、`#1200` の耐水ペーパーで水研ぎします。摩擦熱を抑えながら表面を整え、あえて細かな傷（足）をつけて、上塗り塗料の食いつきを良くします。",
  },
  {
    key: "process.step.6.why",
    page: "process",
    route: "/process",
    label: "工程 / STEP06 「なぜ」 (rich, strong)",
    kind: "rich",
    maxLen: 80,
    defaultText:
      "**なぜ** — つるつるより、わずかに足がある方が塗料は密着します。平滑さと密着の、両立点です。",
  },
  {
    key: "process.step.7.label",
    page: "process",
    route: "/process",
    label: "工程 / STEP07 固定ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "STEP",
  },
  {
    key: "process.step.7.title",
    page: "process",
    route: "/process",
    label: "工程 / STEP07 タイトル",
    kind: "text",
    maxLen: 15,
    defaultText: "ベースコート（色）",
  },
  {
    key: "process.step.7.en",
    page: "process",
    route: "/process",
    label: "工程 / STEP07 英字ラベル",
    kind: "text",
    maxLen: 15,
    defaultText: "BASE COAT",
  },
  {
    key: "process.step.7.desc",
    page: "process",
    route: "/process",
    label: "工程 / STEP07 説明文",
    kind: "text",
    maxLen: 170,
    defaultText:
      "いよいよ色を吹きます。一度に厚く吹かず、薄く数回に分けて重ねる。塗る方向を層ごとに変え、乾燥間隔（フラッシュタイム）を取りながら発色を積み上げます。メタリック・パールは、この膜厚の管理が仕上がりを左右します。",
  },
  {
    key: "process.step.7.why",
    page: "process",
    route: "/process",
    label: "工程 / STEP07 「なぜ」 (rich, strong ×2)",
    kind: "rich",
    maxLen: 90,
    defaultText:
      "**なぜ** — 厚塗りはタレ・ゆず肌・ディテールの潰れを招く。**薄く、数回。**これが均一な発色の条件です。",
  },
  {
    key: "process.step.8.label",
    page: "process",
    route: "/process",
    label: "工程 / STEP08 固定ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "STEP",
  },
  {
    key: "process.step.8.title",
    page: "process",
    route: "/process",
    label: "工程 / STEP08 タイトル",
    kind: "text",
    maxLen: 10,
    defaultText: "クリアコート",
  },
  {
    key: "process.step.8.en",
    page: "process",
    route: "/process",
    label: "工程 / STEP08 英字ラベル",
    kind: "text",
    maxLen: 40,
    defaultText: "CLEAR COAT — 2K URETHANE",
  },
  {
    key: "process.step.8.desc",
    page: "process",
    route: "/process",
    label: "工程 / STEP08 説明文",
    kind: "text",
    maxLen: 155,
    defaultText:
      "2液ウレタンクリアを吹きます。3コートパールの場合は、ベースとクリアの間にパール層を挟みます。主剤と硬化剤が反応し、硬く平滑な塗膜そのものを形成する——だから、吹きっぱなしで深い艶が出ます。",
  },
  {
    key: "process.step.8.why",
    page: "process",
    route: "/process",
    label: "工程 / STEP08 「なぜ」 (rich, strong ×2)",
    kind: "rich",
    maxLen: 105,
    defaultText:
      "**なぜ** — 2液ウレタンは磨かずとも光る。**だから鏡面磨きをしません。**その時間を、数量対応と価格の還元に回します。",
  },
  {
    key: "process.step.9.label",
    page: "process",
    route: "/process",
    label: "工程 / STEP09 固定ラベル",
    kind: "text",
    maxLen: 10,
    defaultText: "STEP",
  },
  {
    key: "process.step.9.title",
    page: "process",
    route: "/process",
    label: "工程 / STEP09 タイトル",
    kind: "text",
    maxLen: 20,
    defaultText: "常温硬化・検品・発送",
  },
  {
    key: "process.step.9.en",
    page: "process",
    route: "/process",
    label: "工程 / STEP09 英字ラベル",
    kind: "text",
    maxLen: 30,
    defaultText: "CURING & SHIPPING",
  },
  {
    key: "process.step.9.desc",
    page: "process",
    route: "/process",
    label: "工程 / STEP09 説明文",
    kind: "text",
    maxLen: 145,
    defaultText:
      "2液ウレタンを常温で5〜7日かけて完全硬化させます。硬化を確認したら、発送前の検品へ。タレ・ゆず肌・色ムラ・異物・密着・エッジ・硬化——項目を確認し、養生・梱包して発送します。",
  },
  {
    key: "process.step.9.why",
    page: "process",
    route: "/process",
    label: "工程 / STEP09 「なぜ」 (rich, strong ×2)",
    kind: "rich",
    maxLen: 105,
    defaultText:
      "**なぜ** — 硬化を待たずに送れば、輸送で傷みます。**急がば、回る。**完全硬化を待つのは、届いてからの品質のためです。",
  },

  // --- SEC.03 THE BOOTH ---
  {
    key: "process.sec.3.label",
    page: "process",
    route: "/process",
    label: "工程 / SEC.03 セクションラベル",
    kind: "text",
    maxLen: 15,
    defaultText: "THE BOOTH",
  },
  {
    key: "process.booth.lead",
    page: "process",
    route: "/process",
    label: "工程 / THE BOOTH リード文",
    kind: "text",
    maxLen: 165,
    defaultText:
      "塗装の大敵は、宙を舞うホコリです。だから塗装は、専用のブースの中で行います。フィルターを通した清浄な空気を上から下へ流し、オーバーミストとともに床下へ排気する——異物混入をふせぐ、目に見えない設備です。",
  },
  {
    key: "process.booth.fact.1.num",
    page: "process",
    route: "/process",
    label: "工程 / BOOTHファクト1 数値",
    kind: "text",
    maxLen: 10,
    defaultText: "5",
  },
  {
    key: "process.booth.fact.1.unit",
    page: "process",
    route: "/process",
    label: "工程 / BOOTHファクト1 単位",
    kind: "text",
    maxLen: 10,
    defaultText: "ミクロン",
  },
  {
    key: "process.booth.fact.1.label",
    page: "process",
    route: "/process",
    label: "工程 / BOOTHファクト1 説明文",
    kind: "text",
    maxLen: 30,
    defaultText: "二次フィルターが捕集する埃の大きさ",
  },
  {
    key: "process.booth.fact.1.en",
    page: "process",
    route: "/process",
    label: "工程 / BOOTHファクト1 英字ラベル",
    kind: "text",
    maxLen: 25,
    defaultText: "DUST CAPTURED",
  },
  {
    key: "process.booth.fact.2.num",
    page: "process",
    route: "/process",
    label: "工程 / BOOTHファクト2 数値",
    kind: "text",
    maxLen: 10,
    defaultText: "90",
  },
  {
    key: "process.booth.fact.2.unit",
    page: "process",
    route: "/process",
    label: "工程 / BOOTHファクト2 単位",
    kind: "text",
    maxLen: 10,
    defaultText: "%超",
  },
  {
    key: "process.booth.fact.2.label",
    page: "process",
    route: "/process",
    label: "工程 / BOOTHファクト2 説明文",
    kind: "text",
    maxLen: 30,
    defaultText: "一次フィルターの外気ダスト捕集率",
  },
  {
    key: "process.booth.fact.2.en",
    page: "process",
    route: "/process",
    label: "工程 / BOOTHファクト2 英字ラベル",
    kind: "text",
    maxLen: 25,
    defaultText: "PRIMARY FILTER",
  },
  {
    key: "process.booth.fact.3.num",
    page: "process",
    route: "/process",
    label: "工程 / BOOTHファクト3 数値 (単位なし)",
    kind: "text",
    maxLen: 10,
    defaultText: "上→下",
  },
  {
    key: "process.booth.fact.3.label",
    page: "process",
    route: "/process",
    label: "工程 / BOOTHファクト3 説明文",
    kind: "text",
    maxLen: 25,
    defaultText: "清浄空気の流れ（ダウンフロー）",
  },
  {
    key: "process.booth.fact.3.en",
    page: "process",
    route: "/process",
    label: "工程 / BOOTHファクト3 英字ラベル",
    kind: "text",
    maxLen: 30,
    defaultText: "DOWNDRAFT AIRFLOW",
  },
  {
    key: "process.booth.note",
    page: "process",
    route: "/process",
    label: "工程 / THE BOOTH 注記",
    kind: "text",
    maxLen: 110,
    defaultText:
      "※ 一般的な自動車塗装ブースの仕組みです。それでも極小のゴミは付着し得るため、最終的な確認は検品工程（サービスページ参照）で行います。",
  },

  // --- SEC.04 RELATED ---
  {
    key: "process.sec.4.label",
    page: "process",
    route: "/process",
    label: "工程 / SEC.04 セクションラベル",
    kind: "text",
    maxLen: 15,
    defaultText: "RELATED",
  },
  {
    key: "process.related.lead",
    page: "process",
    route: "/process",
    label: "工程 / RELATED リード文",
    kind: "text",
    maxLen: 125,
    defaultText:
      "グレード別の料金や数量スライドはサービスページに、素材ごとの下地の作り分けは素材対応ページにまとめています。工程の思想を、色の実例で見たいときは色見本へ。",
  },
  {
    key: "process.related.link.1",
    page: "process",
    route: "/process",
    label: "工程 / RELATED リンク1 文言 (→/service)",
    kind: "text",
    maxLen: 15,
    defaultText: "サービス・料金",
  },
  {
    key: "process.related.link.2",
    page: "process",
    route: "/process",
    label: "工程 / RELATED リンク2 文言 (→/materials)",
    kind: "text",
    maxLen: 10,
    defaultText: "素材対応",
  },
  {
    key: "process.related.link.3",
    page: "process",
    route: "/process",
    label: "工程 / RELATED リンク3 文言 (→/colors)",
    kind: "text",
    maxLen: 10,
    defaultText: "色見本",
  },

  // --- GALLERY ---
  {
    key: "process.sec.5.label",
    page: "process",
    route: "/process",
    label: "工程 / GALLERY セクションラベル",
    kind: "text",
    maxLen: 30,
    defaultText: "BEHIND THE STEPS",
  },
  {
    key: "process.gallery.lead",
    page: "process",
    route: "/process",
    label: "工程 / GALLERY リード文",
    kind: "text",
    maxLen: 55,
    defaultText: "地味な工程の積み重ねが、量産品と見分けがつかない顔をつくります。",
  },
  {
    key: "process.gallery.1.capja",
    page: "process",
    route: "/process",
    label: "工程 / FIG.03 日本語キャプション",
    kind: "text",
    maxLen: 10,
    defaultText: "設備",
  },
  {
    key: "process.gallery.1.capen",
    page: "process",
    route: "/process",
    label: "工程 / FIG.03 英語キャプション",
    kind: "text",
    maxLen: 25,
    defaultText: "SPRAY EQUIPMENT",
  },
  {
    key: "process.gallery.1.credit",
    page: "process",
    route: "/process",
    label: "工程 / FIG.03 クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: kagan_4854 / Unsplash",
  },
  {
    key: "process.gallery.2.capja",
    page: "process",
    route: "/process",
    label: "工程 / FIG.04 日本語キャプション",
    kind: "text",
    maxLen: 10,
    defaultText: "精度",
  },
  {
    key: "process.gallery.2.capen",
    page: "process",
    route: "/process",
    label: "工程 / FIG.04 英語キャプション",
    kind: "text",
    maxLen: 15,
    defaultText: "PRECISION",
  },
  {
    key: "process.gallery.2.credit",
    page: "process",
    route: "/process",
    label: "工程 / FIG.04 クレジット表記",
    kind: "text",
    maxLen: 45,
    defaultText: "Photo: kadircelep / Unsplash",
  },
  {
    key: "process.gallery.3.capja",
    page: "process",
    route: "/process",
    label: "工程 / FIG.05 日本語キャプション",
    kind: "text",
    maxLen: 10,
    defaultText: "質感",
  },
  {
    key: "process.gallery.3.capen",
    page: "process",
    route: "/process",
    label: "工程 / FIG.05 英語キャプション",
    kind: "text",
    maxLen: 20,
    defaultText: "THE SURFACE",
  },
  {
    key: "process.gallery.3.credit",
    page: "process",
    route: "/process",
    label: "工程 / FIG.05 クレジット表記",
    kind: "text",
    maxLen: 50,
    defaultText: "Photo: apryan_cahyo / Unsplash",
  },
];
