import type { PageTextSlot } from "../types";

// ---------------------------------------------------------------------------
// shared / chrome (2) — route 横断の共有スロット (PLAN.md §2.2)
// ---------------------------------------------------------------------------
export const SHARED_CHROME_TEXT_SLOTS: readonly PageTextSlot[] = [
  {
    key: "shared.cta.consult",
    page: "shared",
    route: "/",
    label: "共通 / 「相談する」ボタン",
    kind: "text",
    maxLen: 8,
    defaultText: "相談する",
    affectsAllRoutes: true,
  },
  {
    key: "chrome.footer.tagline",
    page: "chrome",
    route: "/",
    label: "共通 / フッター事業紹介文",
    kind: "multiline",
    maxLen: 80,
    defaultText:
      "3Dプリント造形物の表面処理(研磨・塗装)専門工房。積層痕除去から自動車グレードの仕上げまで、郵送で全国からお受けします。",
    affectsAllRoutes: true,
  },

  // ---------------------------------------------------------------------------
  // common.header (20) — SiteHeader (site-header.tsx) 全表示テキスト (v2 Wave 1 W1-1)
  // ---------------------------------------------------------------------------
  {
    key: "common.header.brand",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーブランド名",
    kind: "text",
    maxLen: 8,
    defaultText: "隈部塗装",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.brand.en",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーブランド名 (英字)",
    kind: "text",
    maxLen: 20,
    defaultText: "KUMABE TOSO",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.1.no",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ1 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "01",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.1.label",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ1 ラベル (ストーリー)",
    kind: "text",
    maxLen: 10,
    defaultText: "ストーリー",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.2.no",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ2 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "02",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.2.label",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ2 ラベル (会社案内)",
    kind: "text",
    maxLen: 8,
    defaultText: "会社案内",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.3.no",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ3 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "03",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.3.label",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ3 ラベル (サービス・料金)",
    kind: "text",
    maxLen: 14,
    defaultText: "サービス・料金",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.4.no",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ4 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "04",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.4.label",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ4 ラベル (施工事例)",
    kind: "text",
    maxLen: 8,
    defaultText: "施工事例",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.5.no",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ5 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "05",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.5.label",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ5 ラベル (お客様の声)",
    kind: "text",
    maxLen: 10,
    defaultText: "お客様の声",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.6.no",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ6 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "06",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.6.label",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ6 ラベル (素材対応)",
    kind: "text",
    maxLen: 8,
    defaultText: "素材対応",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.7.no",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ7 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "07",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.7.label",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ7 ラベル (色見本)",
    kind: "text",
    maxLen: 8,
    defaultText: "色見本",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.8.no",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ8 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "08",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.8.label",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ8 ラベル (読みもの)",
    kind: "text",
    maxLen: 8,
    defaultText: "読みもの",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.9.no",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ9 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "09",
    affectsAllRoutes: true,
  },
  {
    key: "common.header.nav.9.label",
    page: "chrome",
    route: "/",
    label: "共通 / ヘッダーナビ9 ラベル (SHOP)",
    kind: "text",
    maxLen: 8,
    defaultText: "SHOP",
    affectsAllRoutes: true,
  },

  // ---------------------------------------------------------------------------
  // common.footer (39) — SiteFooter (site-footer.tsx) 全表示テキスト (v2 Wave 1 W1-1)
  // ---------------------------------------------------------------------------
  {
    key: "common.footer.marquee.1",
    page: "chrome",
    route: "/",
    label: "共通 / フッターマーキー1",
    kind: "text",
    maxLen: 40,
    defaultText: "研磨 · 塗装 · 3Dプリント表面処理",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.marquee.2",
    page: "chrome",
    route: "/",
    label: "共通 / フッターマーキー2",
    kind: "text",
    maxLen: 36,
    defaultText: "NATIONWIDE MAIL-IN",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.marquee.3",
    page: "chrome",
    route: "/",
    label: "共通 / フッターマーキー3",
    kind: "text",
    maxLen: 32,
    defaultText: "OITA BUNGOTAKADA",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.marquee.4",
    page: "chrome",
    route: "/",
    label: "共通 / フッターマーキー4",
    kind: "text",
    maxLen: 38,
    defaultText: "試作1点 — ブリッジ生産1,000個",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.1.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ1 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "00",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.1.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ1 ラベル (ホーム)",
    kind: "text",
    maxLen: 8,
    defaultText: "ホーム",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.2.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ2 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "01",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.2.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ2 ラベル (ストーリー)",
    kind: "text",
    maxLen: 10,
    defaultText: "ストーリー",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.3.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ3 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "02",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.3.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ3 ラベル (会社案内)",
    kind: "text",
    maxLen: 8,
    defaultText: "会社案内",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.4.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ4 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "03",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.4.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ4 ラベル (サービス・料金)",
    kind: "text",
    maxLen: 14,
    defaultText: "サービス・料金",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.5.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ5 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "04",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.5.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ5 ラベル (施工事例)",
    kind: "text",
    maxLen: 8,
    defaultText: "施工事例",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.6.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ6 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "05",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.6.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ6 ラベル (お客様の声)",
    kind: "text",
    maxLen: 10,
    defaultText: "お客様の声",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.7.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ7 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "06",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.7.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ7 ラベル (工程)",
    kind: "text",
    maxLen: 8,
    defaultText: "工程",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.8.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ8 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "07",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.8.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ8 ラベル (素材対応)",
    kind: "text",
    maxLen: 8,
    defaultText: "素材対応",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.9.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ9 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "08",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.9.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ9 ラベル (色見本)",
    kind: "text",
    maxLen: 8,
    defaultText: "色見本",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.10.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ10 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "09",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.10.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ10 ラベル (読みもの)",
    kind: "text",
    maxLen: 8,
    defaultText: "読みもの",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.11.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ11 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "10",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.11.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ11 ラベル (SHOP)",
    kind: "text",
    maxLen: 8,
    defaultText: "SHOP",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.12.no",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ12 番号",
    kind: "text",
    maxLen: 4,
    defaultText: "11",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.nav.12.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッターナビ12 ラベル (相談する)",
    kind: "text",
    maxLen: 8,
    defaultText: "相談する",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.sitemap.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッター SITEMAP 見出し",
    kind: "text",
    maxLen: 14,
    defaultText: "SITEMAP",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.workshop.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッター WORKSHOP 見出し",
    kind: "text",
    maxLen: 16,
    defaultText: "WORKSHOP",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.legal.label",
    page: "chrome",
    route: "/",
    label: "共通 / フッター LEGAL 見出し",
    kind: "text",
    maxLen: 10,
    defaultText: "LEGAL",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.brand",
    page: "chrome",
    route: "/",
    label: "共通 / フッター会社名",
    kind: "text",
    maxLen: 8,
    defaultText: "隈部塗装",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.address",
    page: "chrome",
    route: "/",
    label: "共通 / フッター住所ブロック",
    kind: "lines",
    maxLen: 60,
    defaultText: "隈部塗装(代表: 隈部 信之)\n大分県豊後高田市\n郵送受託・全国対応",
    maxLines: 3,
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.legal.tokushoho",
    page: "chrome",
    route: "/",
    label: "共通 / フッター LEGAL リンク (特定商取引法)",
    kind: "text",
    maxLen: 24,
    defaultText: "特定商取引法に基づく表記",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.legal.privacy",
    page: "chrome",
    route: "/",
    label: "共通 / フッター LEGAL リンク (プライバシーポリシー)",
    kind: "text",
    maxLen: 20,
    defaultText: "プライバシーポリシー",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.giant",
    page: "chrome",
    route: "/",
    label: "共通 / フッター装飾巨大文字",
    kind: "text",
    maxLen: 16,
    defaultText: "KUMABE TOSO",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.copyright",
    page: "chrome",
    route: "/",
    label: "共通 / フッターコピーライト",
    kind: "text",
    maxLen: 60,
    defaultText: "© 2026 KUMABE TOSO. ALL RIGHTS RESERVED.",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.copyright.sub",
    page: "chrome",
    route: "/",
    label: "共通 / フッターコピーライト補足",
    kind: "text",
    maxLen: 60,
    defaultText: "3D PRINT SURFACE FINISHING — OITA, JAPAN",
    affectsAllRoutes: true,
  },
  {
    key: "common.footer.creditNote",
    page: "chrome",
    route: "/",
    label: "共通 / フッター写真クレジット注記",
    kind: "multiline",
    maxLen: 150,
    defaultText:
      "掲載写真は Unsplash の商用利用可能なイメージ素材で、各写真のクレジットはキャプションに記載しています。これらは隈部塗装の工房・制作事例の写真ではなく、あくまでイメージです(実際の写真は準備中)。",
    affectsAllRoutes: true,
  },
];
