import type { PageTextSlot } from "../types";

// ---------------------------------------------------------------------------
// shop (9, route: "/shop")
// ---------------------------------------------------------------------------
export const SHOP_TEXT_SLOTS: readonly PageTextSlot[] = [
  {
    key: "shop.hero.heading",
    page: "shop",
    route: "/shop",
    label: "SHOP / ヒーロー見出し",
    kind: "lines",
    maxLen: 26,
    defaultText: "仕上げを、\n通販のように買う。",
    maxLines: 2,
    maxLineLen: 20,
  },
  {
    key: "shop.hero.lead",
    page: "shop",
    route: "/shop",
    label: "SHOP / ヒーローリード文",
    kind: "multiline",
    maxLen: 200,
    defaultText:
      "受託の表面仕上げを、商品のように選べるようにしました。グレードを選び、サイズと個数で概算を出し、そのまま注文のご相談へ。オンライン決済は現在準備中のため、いまは「注文の意思表示 → 相談 → 正式見積もり → お支払い」の流れでお受けしています。手のひらの造形物を送るだけで、量産品の顔になって還ってきます。",
  },
  {
    key: "shop.grades.heading",
    page: "shop",
    route: "/shop",
    label: "SHOP / FINISHING SERVICES 見出し",
    kind: "lines",
    maxLen: 24,
    defaultText: "3つのグレードから、\n選ぶ。",
    maxLines: 2,
  },
  {
    key: "shop.simulator.heading",
    page: "shop",
    route: "/shop",
    label: "SHOP / ESTIMATE SIMULATOR 見出し",
    kind: "lines",
    maxLen: 30,
    defaultText: "サイズ × 個数 × グレード。\n3つ選べば、概算が出る。",
    maxLines: 2,
    maxLineLen: 16,
  },
  {
    key: "shop.simulator.cta",
    page: "shop",
    route: "/shop",
    label: "SHOP / シミュレータ注文ボタン (固定高+矢印、折返し厳禁)",
    kind: "text",
    maxLen: 16,
    defaultText: "この内容で注文・相談する",
  },
  {
    key: "shop.products.heading",
    page: "shop",
    route: "/shop",
    label: "SHOP / READY-MADE 見出し",
    kind: "lines",
    maxLen: 24,
    defaultText: "手に取れる製品も、\nここに並びます。",
    maxLines: 2,
  },
  {
    key: "shop.flow.heading",
    page: "shop",
    route: "/shop",
    label: "SHOP / HOW TO ORDER 見出し",
    kind: "text",
    maxLen: 20,
    defaultText: "注文から、お届けまで。",
  },
  {
    key: "shop.cta.heading",
    page: "shop",
    route: "/shop",
    label: "SHOP / CTA帯 見出し",
    kind: "lines",
    maxLen: 44,
    defaultText: "概算が出たら、\nあとは送るだけ。",
    maxLines: 2,
  },
  {
    key: "shop.cta.note",
    page: "shop",
    route: "/shop",
    label: "SHOP / CTA帯 補足",
    kind: "text",
    maxLen: 60,
    defaultText: "シミュレータの内容をコピーして、そのまま貼り付けてご相談ください。",
  },
];
